'use client';

import { useState } from 'react';
import axios from 'axios';
import { 
  Loader2, ArrowRight, Activity, Utensils, Lock, 
  CheckCircle2, X, Download, ShieldCheck, 
  Sparkles, ShoppingBag, Calendar, RefreshCcw, 
  Droplets, Moon, Zap, HeartPulse, Leaf
} from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { toast } from '@/lib/safe-toast';
import { useRouter } from 'next/navigation';
import jsPDF from 'jspdf'; 

// --- UI HELPERS ---

const MealRow = ({ label, value }: { label: string, value: string }) => (
  <div className="flex gap-3 items-start text-sm py-1.5 border-b border-slate-50 last:border-0">
    <span className="font-bold text-slate-400 w-20 shrink-0 text-xs uppercase tracking-wider">{label}</span>
    <span className="text-slate-800 font-medium text-sm leading-snug line-clamp-2">
      {value && value.length > 2 ? value : <span className="text-slate-300 italic">Tap to view details</span>}
    </span>
  </div>
);

const LifestyleIcon = ({ type }: { type: string }) => {
  const t = type?.toLowerCase() || '';
  if (t.includes('hydrat')) return <Droplets className="text-blue-500" size={20} />;
  if (t.includes('sleep') || t.includes('rest')) return <Moon className="text-indigo-500" size={20} />;
  if (t.includes('activ') || t.includes('exerc')) return <Zap className="text-yellow-500" size={20} />;
  if (t.includes('nutri') || t.includes('food')) return <Leaf className="text-green-500" size={20} />;
  return <HeartPulse className="text-rose-500" size={20} />;
};

// --- MAIN COMPONENT ---

export default function LatestHealthWidget({ order }: { order: any }) {
  const router = useRouter();
  const [generating, setGenerating] = useState(false);
  const [showDietModal, setShowDietModal] = useState(false);
  
  // Safe Parse JSON
  const [aiData, setAiData] = useState<any>(() => {
    try { 
      return order?.reportSummary?.content ? JSON.parse(order.reportSummary.content) : null; 
    } catch { return null; }
  });

  const hasDiet = !!(aiData?.dietPlan?.plan?.length > 0);
  const score = aiData?.healthScore || 0;
  const reportCount = aiData?.reportCount || 1;
  const firstDay = hasDiet ? aiData.dietPlan.plan[0] : {};
  const todayName = firstDay.day || "Day 1";

  const handleGenerate = async () => {
    setGenerating(true);
    try {
      const res = await axios.post('/api/ai/generate-diet', { orderId: order.id });
      setAiData(res.data);
      if (res.data.dietPlan) setShowDietModal(true);
      
      if (res.data.cached) toast.info("Profile is up to date.");
      else toast.success("Health Analysis Updated!");
    } catch (e) {
      toast.error("Analysis failed. Try again.");
    } finally {
      setGenerating(false);
    }
  };

  const downloadPDF = () => {
    if (!hasDiet) return;
    const doc = new jsPDF();
    doc.setFontSize(22);
    doc.text("Personalized Wellness Plan", 20, 20);
    doc.setFontSize(10);
    doc.text(`Generated by MediAI • Order #${order.orderNumber || 'N/A'}`, 20, 30);
    
    let y = 50;
    aiData.dietPlan.plan.forEach((day: any, index: number) => {
      if (y > 270) { doc.addPage(); y = 20; }
      doc.setFont("helvetica", "bold");
      doc.text(day.day || `Day ${index + 1}`, 20, y);
      y += 8;
      doc.setFont("helvetica", "normal");
      doc.text(`• Breakfast: ${day.breakfast || '-'}`, 25, y);
      doc.text(`• Lunch: ${day.lunch || '-'}`, 25, y + 6);
      doc.text(`• Dinner: ${day.dinner || '-'}`, 25, y + 12);
      y += 25;
    });
    doc.save(`Diet_Plan_${order.orderNumber}.pdf`);
  };

  if (!order || !aiData) return null;

  return (
    <>
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 mb-8">
        
        {/* === LEFT CARD: HEALTH SCORE & LIFESTYLE === */}
        <motion.div 
          initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}
          className="lg:col-span-2 bg-white border border-slate-100 rounded-[2rem] p-8 shadow-sm relative overflow-hidden flex flex-col justify-between"
        >
          {/* Background decoration */}
          <div className="absolute top-0 right-0 p-10 opacity-[0.03] pointer-events-none">
            <Activity size={300} />
          </div>

          <div className="flex flex-col md:flex-row items-center gap-8 z-10">
            {/* Score Circle */}
            <div className="relative size-44 shrink-0">
               <svg className="size-full -rotate-90" viewBox="0 0 36 36">
                 <path className="text-slate-100" d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831" fill="none" stroke="currentColor" strokeWidth="2.5" />
                 <path 
                   className={`${score > 80 ? 'text-emerald-500' : score > 50 ? 'text-amber-500' : 'text-red-500'} transition-all duration-1000 ease-out`}
                   strokeDasharray={`${score}, 100`}
                   d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831" 
                   fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round"
                 />
               </svg>
               <div className="absolute inset-0 flex flex-col items-center justify-center">
                 <span className="text-5xl font-black text-slate-800">{score}</span>
                 <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mt-1">Score</span>
               </div>
            </div>

            {/* Headline & Buttons */}
            <div className="flex-1 text-center md:text-left">
               <div className="inline-flex items-center gap-2 bg-slate-900 text-white px-3 py-1 rounded-full text-[10px] font-bold uppercase tracking-wider mb-3">
                  <Sparkles size={10} className="text-yellow-400" /> Based on last {reportCount} reports
               </div>
               <h3 className="text-2xl font-bold text-slate-800 mb-2 leading-tight">
                 {aiData.summaryHeadline || "Your health profile is ready."}
               </h3>
               
               <div className="flex flex-wrap justify-center md:justify-start gap-3 mt-4">
                 <button onClick={() => router.push(`/dashboard/orders/${order.id}`)} className="text-sm font-bold text-blue-600 hover:text-blue-800 flex items-center gap-1">
                   View Report <ArrowRight size={16}/>
                 </button>
                 <button onClick={handleGenerate} disabled={generating} className="text-xs font-bold text-slate-400 hover:text-blue-600 flex items-center gap-1 bg-slate-50 px-3 py-1.5 rounded-lg transition-colors border border-slate-100">
                   <RefreshCcw size={12} className={generating ? "animate-spin" : ""} />
                   {generating ? "Checking..." : "Refresh Analysis"}
                 </button>
               </div>
            </div>
          </div>

          {/* LIFESTYLE SECTION GRID */}
          {aiData.lifestyle && aiData.lifestyle.length > 0 && (
             <div className="mt-8 pt-6 border-t border-slate-100 grid grid-cols-1 sm:grid-cols-3 gap-4">
                {aiData.lifestyle.map((item: any, i: number) => (
                  <div key={i} className="flex items-center gap-3 bg-slate-50 p-3 rounded-2xl border border-slate-100">
                      <div className="w-10 h-10 bg-white rounded-xl flex items-center justify-center shadow-sm">
                        <LifestyleIcon type={item.icon} />
                      </div>
                      <div className="min-w-0">
                        <div className="text-xs font-bold text-slate-800 truncate">{item.title}</div>
                        <div className="text-[10px] text-slate-500 leading-tight mt-0.5 line-clamp-2">{item.desc}</div>
                      </div>
                  </div>
                ))}
             </div>
          )}
        </motion.div>

        {/* === RIGHT CARD: DIET PLAN PREVIEW === */}
        <motion.div 
          initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.1 }}
          className={`rounded-[2rem] p-6 flex flex-col justify-between relative overflow-hidden border ${
            hasDiet ? 'bg-gradient-to-br from-emerald-50 to-white border-emerald-100' : 'bg-slate-900 text-white border-slate-800'
          }`}
        >
          {hasDiet ? (
             <>
               <div>
                 <div className="flex items-center justify-between mb-4">
                   <div className="flex items-center gap-2 text-emerald-800 font-bold">
                     <div className="p-1.5 bg-emerald-100 rounded-lg"><Utensils size={16} /></div>
                     Today's Plan
                   </div>
                   <span className="text-[10px] font-bold bg-white px-2 py-1 rounded border border-emerald-100 text-emerald-600 uppercase truncate max-w-[80px]">
                     {todayName}
                   </span>
                 </div>
                 
                 <div className="bg-white/80 p-4 rounded-2xl border border-emerald-50 shadow-sm space-y-1 backdrop-blur-sm">
                    <MealRow label="Breakfst" value={firstDay.breakfast} />
                    <MealRow label="Lunch" value={firstDay.lunch} />
                    <MealRow label="Dinner" value={firstDay.dinner} />
                 </div>
               </div>
               <button onClick={() => setShowDietModal(true)} className="mt-4 w-full py-3 bg-emerald-600 text-white rounded-xl text-xs font-bold hover:bg-emerald-700 transition-all">
                 Open Full Week Plan
               </button>
             </>
          ) : (
             <>
                <div className="absolute top-0 right-0 p-6 opacity-10 rotate-12"><Lock size={120} /></div>
                <div className="relative z-10 flex flex-col h-full justify-center">
                   <div className="w-12 h-12 bg-white/10 rounded-2xl flex items-center justify-center mb-4 text-emerald-400 backdrop-blur-md">
                     <Utensils size={24} />
                   </div>
                   <h3 className="text-xl font-bold mb-2">Personalized Diet</h3>
                   <p className="text-slate-400 text-sm mb-8 leading-relaxed">
                     Unlock a 7-day meal plan designed to improve your health score.
                   </p>
                   <button onClick={handleGenerate} disabled={generating} className="w-full bg-emerald-500 hover:bg-emerald-400 text-white py-3.5 rounded-xl font-bold text-sm transition-all flex items-center justify-center gap-2">
                     {generating ? <Loader2 className="animate-spin"/> : <CheckCircle2 size={18} />}
                     {generating ? 'Analyzing...' : 'Unlock for Free'}
                   </button>
                </div>
             </>
          )}
        </motion.div>
      </div>

      {/* === RECOMMENDATIONS SECTION === */}
      {aiData.recommendations && aiData.recommendations.length > 0 && (
        <motion.div 
          initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }}
          className="mb-8"
        >
           <div className="flex items-center gap-2 mb-4 px-1">
              <Sparkles className="text-blue-600 fill-blue-600" size={18} />
              <h3 className="font-bold text-slate-800 text-lg">Recommended for You</h3>
           </div>
           
           <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {aiData.recommendations.map((rec: any, idx: number) => (
                 <div key={idx} className="bg-white border border-slate-100 p-5 rounded-2xl flex flex-col sm:flex-row justify-between items-center gap-4 shadow-sm hover:shadow-md transition-shadow group">
                    <div className="flex items-start gap-4 w-full">
                       <div className="w-12 h-12 rounded-xl bg-blue-50 text-blue-600 flex items-center justify-center shrink-0 group-hover:bg-blue-600 group-hover:text-white transition-colors">
                          <ShoppingBag size={20} />
                       </div>
                       <div className="min-w-0">
                          <div className="flex items-center gap-2 mb-1">
                             <span className="text-[10px] font-bold bg-slate-100 text-slate-500 px-1.5 py-0.5 rounded uppercase">{rec.type}</span>
                             <h4 className="font-bold text-slate-800 truncate">{rec.name}</h4>
                          </div>
                          <p className="text-xs text-slate-500 leading-relaxed max-w-sm line-clamp-2">{rec.reason}</p>
                       </div>
                    </div>
                    
                    <div className="text-right flex flex-row sm:flex-col items-center sm:items-end gap-3 w-full sm:w-auto justify-between">
                       {rec.isBookable ? (
                           <div className="font-bold text-lg text-slate-900">₹{rec.price}</div>
                       ) : (
                           <div className="text-[10px] text-slate-400 italic">Not in catalog</div>
                       )}
                       
                       <button 
                         onClick={() => router.push(`/search?q=${encodeURIComponent(rec.name)}`)} 
                         className="bg-slate-900 text-white px-5 py-2 rounded-lg text-xs font-bold hover:bg-black transition-transform active:scale-95 whitespace-nowrap"
                       >
                         {rec.isBookable ? 'Book Now' : 'Search Test'}
                       </button>
                    </div>
                 </div>
              ))}
           </div>
        </motion.div>
      )}

      {/* === DIET MODAL (Full Week) === */}
      <AnimatePresence>
        {showDietModal && hasDiet && (
          <div className="fixed inset-0 z-[60] flex items-center justify-center p-4">
             <motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={() => setShowDietModal(false)} className="absolute inset-0 bg-slate-900/60 backdrop-blur-sm" />
             
             <motion.div initial={{scale:0.95, y:20}} animate={{scale:1, y:0}} exit={{scale:0.95, y:20}} className="bg-white w-full max-w-3xl max-h-[85vh] overflow-hidden rounded-3xl shadow-2xl relative z-10 flex flex-col">
                <div className="p-6 border-b border-slate-100 flex justify-between items-center bg-slate-50">
                   <div>
                      <h2 className="text-xl font-bold text-slate-800">Your Wellness Plan</h2>
                      <p className="text-xs text-slate-500 mt-1 flex items-center gap-1"><ShieldCheck size={12} className="text-emerald-600"/> AI Analysis of {reportCount} reports</p>
                   </div>
                   <button onClick={() => setShowDietModal(false)} className="p-2 bg-white rounded-full shadow-sm text-slate-400 hover:text-slate-600 hover:rotate-90 transition-all"><X size={20}/></button>
                </div>

                <div className="flex-1 overflow-y-auto p-6 space-y-6 bg-white">
                   <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                      <div className="bg-emerald-50 p-5 rounded-2xl border border-emerald-100">
                         <h4 className="font-bold text-emerald-800 text-sm mb-3 flex items-center gap-2"><CheckCircle2 size={16}/> Foods to Include</h4>
                         <div className="flex flex-wrap gap-2">{aiData.dietPlan.include?.map((item:string, i:number) => (<span key={i} className="bg-white px-2 py-1 rounded-md text-xs font-medium text-emerald-700 shadow-sm">{item}</span>))}</div>
                      </div>
                      <div className="bg-red-50 p-5 rounded-2xl border border-red-100">
                         <h4 className="font-bold text-red-800 text-sm mb-3 flex items-center gap-2"><X size={16}/> Foods to Avoid</h4>
                         <div className="flex flex-wrap gap-2">{aiData.dietPlan.avoid?.map((item:string, i:number) => (<span key={i} className="bg-white px-2 py-1 rounded-md text-xs font-medium text-red-700 shadow-sm">{item}</span>))}</div>
                      </div>
                   </div>

                   <h3 className="font-bold text-slate-800 text-lg flex items-center gap-2"><Calendar size={20} className="text-blue-600"/> Weekly Schedule</h3>
                   <div className="space-y-3">
                      {aiData.dietPlan.plan.map((day: any, i: number) => (
                         <div key={i} className="border border-slate-100 rounded-2xl p-5 hover:bg-slate-50 transition-colors group">
                            <h4 className="font-bold text-slate-900 mb-3 text-sm flex items-center gap-2">
                              <span className="w-6 h-6 rounded-full bg-blue-100 text-blue-600 flex items-center justify-center text-xs">{i+1}</span>
                              {day.day || `Day ${i+1}`}
                            </h4>
                            <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-xs">
                               <div className="flex flex-col gap-1">
                                 <span className="font-bold text-slate-400 uppercase tracking-wider text-[10px]">Breakfast</span> 
                                 <span className="text-slate-700 font-medium group-hover:text-blue-700">{day.breakfast || "See details"}</span>
                               </div>
                               <div className="flex flex-col gap-1">
                                 <span className="font-bold text-slate-400 uppercase tracking-wider text-[10px]">Lunch</span> 
                                 <span className="text-slate-700 font-medium group-hover:text-blue-700">{day.lunch || "See details"}</span>
                               </div>
                               <div className="flex flex-col gap-1">
                                 <span className="font-bold text-slate-400 uppercase tracking-wider text-[10px]">Dinner</span> 
                                 <span className="text-slate-700 font-medium group-hover:text-blue-700">{day.dinner || "See details"}</span>
                               </div>
                            </div>
                         </div>
                      ))}
                   </div>
                </div>
                
                <div className="p-4 border-t border-slate-100 bg-slate-50 flex justify-between items-center">
                   <p className="text-[10px] text-slate-400 max-w-xs">Not a medical prescription.</p>
                   <button onClick={downloadPDF} className="flex items-center gap-2 bg-slate-900 text-white px-6 py-3 rounded-xl font-bold text-sm hover:bg-black transition-transform active:scale-95"><Download size={16} /> Download PDF</button>
                </div>
             </motion.div>
          </div>
        )}
      </AnimatePresence>
    </>
  );
}