import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🚀 Starting Data Seeding...');

  // ==================================================
  // 1. SEED LABS
  // ==================================================
  const labsData = [
    { id: 7, labName: 'The Health County Labs', city: 'Gurgaon', pincode: '122001', address: '84, 2nd Floor, Sheetla Mata Road, Opp. AVR Invitation Garden', contactNo: '8076468962', email: 'info@thclabs.in', homeCollectionCharges: 200.00 },
    { id: 9, labName: 'Advanced Pathology & Diagnostic Centre', city: 'Farrukhabad', pincode: '209625', address: '1/67, Awas Vikas Colony, Opposite Side Neelkanth Sweet', contactNo: '8756017317', email: '', homeCollectionCharges: 100.00 },
    { id: 11, labName: 'Molq Diagnostic', city: 'Gurgaon', pincode: '122001', address: '123, lab street, Udhyog Vihar', contactNo: '9999888877', email: 'molq@lab.com', homeCollectionCharges: 250.00 },
    { id: 12, labName: 'HealthFirst Center', city: 'Gurgaon', pincode: '122001', address: 'ABC Sector XYZ, Railway Road', contactNo: '9999888877', email: 'user@user.com', homeCollectionCharges: 200.00 }
  ];

  console.log(`🏥 Seeding ${labsData.length} Labs...`);

  for (const lab of labsData) {
    await prisma.lab.upsert({
      where: { id: lab.id },
      update: {}, 
      create: {
        id: lab.id,
        labName: lab.labName,
        city: lab.city,
        pincode: lab.pincode,
        address: lab.address,
        contactNo: lab.contactNo,
        email: lab.email || `lab${lab.id}@placeholder.com`,
        homeCollectionCharges: lab.homeCollectionCharges,
        status: 'Active',
        password: 'password123'
      }
    });
  }

  // ==================================================
  // 2. SEED TESTS
  // ==================================================
  // ✅ FIX: Type explicitly as any[] to allow loose matching
  const testsData: any[] = [
    { id: 651, testName: 'Hepatitis C Virus (HCV Antibody)-Rapid', price: 850.00, category: 'Infectious Diseases' },
    { id: 652, testName: 'Cysticercosis IgG Antibody', price: 3200.00, category: 'Infectious Diseases' },
    { id: 653, testName: 'Sex Hormone Binding Globulin (SHBG)', price: 3800.00, category: 'Hormonal & Endocrine' },
    { id: 654, testName: 'Creatinine - 24 hrs Urine', price: 500.00, category: 'Routine Tests' },
    { id: 655, testName: 'Cytomegalovirus IgG Antibody', price: 750.00, category: 'Infectious Diseases' },
    { id: 656, testName: 'Cytomegalovirus IgM Antibody', price: 750.00, category: 'Infectious Diseases' },
    { id: 657, testName: 'Iron Saturation (%)', price: 1100.00, category: 'Routine Tests' },
    { id: 658, testName: 'Sputum for Malignant Cells', price: 750.00, category: 'Cancer Markers' },
    { id: 659, testName: 'Stool for Hanging Drop-Stool', price: 600.00, category: 'Infectious Diseases' },
    { id: 660, testName: 'Triiodothyronine - Free (FT3)', price: 400.00, category: 'Hormonal & Endocrine' },
    { id: 661, testName: 'Culture, Aerobic - Ascitic Fluid', price: 875.00, category: 'Infectious Diseases' },
    { id: 662, testName: 'Culture, Aerobic - Bronchial lavage', price: 875.00, category: 'Infectious Diseases' },
    { id: 663, testName: 'Thyroglobulin', price: 1350.00, category: 'Hormonal & Endocrine' },
    { id: 664, testName: 'Cytology -FNAC-PUS', price: 1100.00, category: 'Cancer Markers' },
    { id: 665, testName: 'Vitamin- B12 (cyanocobalamin)', price: 1000.00, category: 'Routine Tests' },
    { id: 666, testName: 'Urine-pH', price: 450.00, category: 'Routine Tests' },
    { id: 667, testName: 'Helicobacter Pylorii IgG', price: 2600.00, category: 'Infectious Diseases' },
    { id: 668, testName: 'Thyroxine Free (FT4)', price: 400.00, category: 'Hormonal & Endocrine' },
    { id: 669, testName: 'Microalbumin-24 hrs Urine', price: 875.00, category: 'Routine Tests' },
    { id: 670, testName: 'Phosphorus- 24hrs Urine', price: 650.00, category: 'Routine Tests' },
    { id: 671, testName: 'Helicobacter Pylori IgA', price: 2500.00, category: 'Specialized Tests' },
    { id: 672, testName: 'Helicobacter Pylorii IgM', price: 2500.00, category: 'Specialized Tests' },
    { id: 673, testName: 'TSH (Thyroid Stimulating Hormone)', price: 250.00, category: 'Specialized Tests' },
    { id: 674, testName: 'Hepatitis C Virus (HCV Antibody)', price: 1200.00, category: 'Specialized Tests' },
    { id: 675, testName: 'Mycobacterium Tuberculosis Complex (MTC) & MOTT PCR', price: 2950.00, category: 'Specialized Tests' },
    { id: 676, testName: 'Mycobacterium Tuberculosis Complex (MTC) & MOTT PCR', price: 2950.00, category: 'Specialized Tests' },
    { id: 677, testName: 'Mycobacterium Tuberculosis Complex (MTC) & MOTT PCR (AF)', price: 2950.00, category: 'Specialized Tests' },
    { id: 678, testName: 'Mycobacterium Tuberculosis Complex (MTC) & MOTT PCR (BL)', price: 2950.00, category: 'Specialized Tests' },
    { id: 679, testName: 'Mycobacterium Tuberculosis Complex (MTC) & MOTT PCR (Blood)', price: 2950.00, category: 'Specialized Tests' },
    { id: 680, testName: 'Mycobacterium Tuberculosis Complex (MTC) & MOTT PCR (CSF)', price: 2950.00, category: 'Specialized Tests' },
    { id: 681, testName: 'Mycobacterium Tuberculosis Complex (MTC) & MOTT PCR (PF)', price: 2950.00, category: 'Specialized Tests' },
    { id: 682, testName: 'Mycobacterium Tuberculosis Complex (MTC) & MOTT PCR (SF)', price: 2950.00, category: 'Specialized Tests' },
    { id: 683, testName: 'Mycobacterium Tuberculosis Complex (MTC) & MOTT PCR (Sputum)', price: 2950.00, category: 'Specialized Tests' },
    { id: 684, testName: 'Mycobacterium Tuberculosis Complex (MTC) & MOTT PCR (Tissue)', price: 2950.00, category: 'Specialized Tests' },
    { id: 685, testName: 'Mycobacterium Tuberculosis Complex (MTC) & MOTT PCR (Urine)', price: 2950.00, category: 'Specialized Tests' },
    { id: 686, testName: 'Culture,Aerobic, Semen', price: 600.00, category: 'Specialized Tests' },
    { id: 687, testName: 'Protein/Creatinine Ratio-24 hrs', price: 875.00, category: 'Specialized Tests' },
    { id: 688, testName: 'FSH (Follicle Stimulating Hormone)', price: 550.00, category: 'Specialized Tests' },
    { id: 689, testName: 'Glucose Challenge Test (75 Gms of glucose):Pregnancy', price: 300.00, category: 'Specialized Tests' },
    { id: 690, testName: 'Troponin - I-Rapid', price: 2700.00, category: 'Specialized Tests' },
    { id: 691, testName: 'Troponin - T-Rapid', price: 2700.00, category: 'Specialized Tests' },
    { id: 692, testName: 'Urine - Ketone Bodies', price: 450.00, category: 'Specialized Tests' },
    { id: 693, testName: '25 - Hydroxy Vitamin D', price: 1250.00, category: 'Specialized Tests' },
    { id: 694, testName: 'Cytology -FNAC-Air Dried Smears', price: 1100.00, category: 'Specialized Tests' },
    { id: 695, testName: 'Cytology -FNAC-Aspirated Fluid', price: 1100.00, category: 'Specialized Tests' },
    { id: 696, testName: 'Cytology -PAP-Air Dried Smears', price: 1100.00, category: 'Specialized Tests' },
    { id: 697, testName: 'Cytology -PAP-Fixed Smears', price: 875.00, category: 'Specialized Tests' },
    { id: 698, testName: 'Cytology -PAP -Peritoneal Fluid', price: 875.00, category: 'Specialized Tests' },
    { id: 699, testName: 'Cytology -PAP-Ascitic Fluid', price: 875.00, category: 'Specialized Tests' },
    { id: 700, testName: 'Cytology -PAP-Aspirated Fluid', price: 875.00, category: 'Specialized Tests' },
    { id: 701, testName: 'Cytology -PAP-Pleural', price: 875.00, category: 'Specialized Tests' },
    { id: 702, testName: 'Cytology -PAP-Pus', price: 875.00, category: 'Specialized Tests' },
    { id: 703, testName: 'Cytology -PAP-Synovial', price: 875.00, category: 'Specialized Tests' },
    { id: 704, testName: 'Pregnancy Associated Plasma Protein-A(PAPP-A)', price: 2600.00, category: 'Specialized Tests' },
    { id: 705, testName: 'Cytology -PAP -Ovarian Cyst', price: 850.00, category: 'Specialized Tests' },
    { id: 706, testName: 'Urine-Reducing Substance', price: 350.00, category: 'Specialized Tests' },
    { id: 707, testName: 'Allergy Profile - Drugs, Inhalants, Non-Veg and Vegetarian', price: 7500.00, category: 'Specialized Tests' },
    { id: 708, testName: 'Folate Acid (Vitamin B9)', price: 1000.00, category: 'Specialized Tests' },
    { id: 709, testName: 'Calcium/Creatinine Ratio - Random Urine', price: 500.00, category: 'Specialized Tests' },
    { id: 710, testName: 'Culture and Sensitivity, Urine', price: 500.00, category: 'Specialized Tests' },
    { id: 711, testName: 'Culture, Aerobic - Pericardial Fluid', price: 600.00, category: 'Specialized Tests' },
    { id: 712, testName: 'Culture, Aerobic - Pleural Fluid', price: 600.00, category: 'Specialized Tests' },
    { id: 713, testName: 'Culture, Aerobic - Synovial  Fluid', price: 600.00, category: 'Specialized Tests' },
    { id: 714, testName: 'Culture, Aerobic, Body Fluids', price: 600.00, category: 'Specialized Tests' },
    { id: 715, testName: 'Culture, Aerobic, CSF', price: 600.00, category: 'Specialized Tests' },
    { id: 716, testName: 'Culture, Aerobic, Ear swab', price: 600.00, category: 'Specialized Tests' },
    { id: 717, testName: 'Culture, Aerobic, Eye swab', price: 600.00, category: 'Specialized Tests' },
    { id: 718, testName: 'Culture, Aerobic, Miscellaneous', price: 600.00, category: 'Specialized Tests' },
    { id: 719, testName: 'Adenosine Deaminase (ADA)-Serum', price: 600.00, category: 'Infectious Diseases' },
    { id: 720, testName: 'AFB Stain (ZN Stain)-Sputum', price: 250.00, category: 'Infectious Diseases' },
    { id: 721, testName: 'Adenosine Deaminase (ADA)-AF', price: 600.00, category: 'Infectious Diseases' },
    { id: 722, testName: 'Adenosine Deaminase (ADA)-CSF', price: 600.00, category: 'Infectious Diseases' },
    { id: 723, testName: 'Adenosine Deaminase (ADA)-Pericardial Fluid', price: 600.00, category: 'Infectious Diseases' },
    { id: 724, testName: 'Adenosine Deaminase (ADA)-PF', price: 600.00, category: 'Infectious Diseases' },
    { id: 725, testName: 'Adenosine Deaminase (ADA)-PUS', price: 600.00, category: 'Infectious Diseases' },
    { id: 726, testName: 'Alpha Feto Protein (AFP)', price: 600.00, category: 'Cancer Markers' },
    { id: 727, testName: 'Anti Cyclic Citrullinated Peptide; ANTI CCP', price: 1500.00, category: 'Allergy & Immunology' },
    { id: 728, testName: 'Alanine Transaminase (ALT/IMPT)', price: 150.00, category: 'Routine Tests' },
    { id: 729, testName: 'Absolute Reticulocyte Count', price: 350.00, category: 'Routine Tests' },
    { id: 730, testName: 'ANCA-MPO (Anti Myeloperoxidase Antibodies)', price: 1500.00, category: 'Allergy & Immunology' },
    { id: 731, testName: '17- Alpha Hydroxy Progesterone (17-OHP)', price: 1300.00, category: 'Hormonal & Endocrine' },
    { id: 732, testName: 'Albert Stain (Diptheria Bacilli)-Throat Swab', price: 250.00, category: 'Infectious Diseases' },
    { id: 733, testName: 'AFB Stain (ZN Stain)-Ascitic Fluid', price: 300.00, category: 'Infectious Diseases' },
    { id: 734, testName: 'AFB Stain (ZN Stain)-Body fluids', price: 300.00, category: 'Infectious Diseases' },
    { id: 735, testName: 'Absolute Eosinophil Count', price: 150.00, category: 'Allergy & Immunology' },
    { id: 736, testName: 'Absolute Lymphocyte Count', price: 150.00, category: 'Routine Tests' },
    { id: 737, testName: 'Absolute Neutrophil Count', price: 150.00, category: 'Routine Tests' },
    { id: 738, testName: 'Alkaline Phosphatase', price: 150.00, category: 'Routine Tests' },
    { id: 739, testName: 'ANCA-PR3 (Serin Proteinase 3 AntibodieS)', price: 1500.00, category: 'Allergy & Immunology' },
    { id: 740, testName: 'Amylase-Serum', price: 400.00, category: 'Routine Tests' },
    { id: 741, testName: 'Amylase-Urine Random', price: 400.00, category: 'Routine Tests' },
    { id: 742, testName: 'Angiotensin Converting Enzyme (ACE)', price: 900.00, category: 'Cardiac & Diabetes' },
    { id: 743, testName: 'Amylase-Body Fluid', price: 500.00, category: 'Routine Tests' },
    { id: 744, testName: 'Aldosterone', price: 2200.00, category: 'Hormonal & Endocrine' },
    { id: 745, testName: 'Amphetamine - Urine', price: 975.00, category: 'Specialized Tests' },
    { id: 746, testName: 'AFB Stain (ZN Stain)-Bronchial lavage', price: 250.00, category: 'Infectious Diseases' },
    { id: 747, testName: 'AFB Stain (ZN Stain)-CSF', price: 250.00, category: 'Infectious Diseases' },
    { id: 748, testName: 'AFB Stain (ZN Stain)-Pericardial Fluid', price: 250.00, category: 'Infectious Diseases' },
    { id: 749, testName: 'AFB Stain (ZN Stain)-Peritoneal Fluid', price: 250.00, category: 'Infectious Diseases' },
    { id: 750, testName: 'AFB Stain (ZN Stain)-Pleural Fluid', price: 250.00, category: 'Infectious Diseases' },
    { id: 751, testName: 'AFB Stain (ZN Stain)-PUS', price: 250.00, category: 'Infectious Diseases' },
    { id: 752, testName: 'AFB Stain (ZN Stain)-Synovial Fluid', price: 250.00, category: 'Infectious Diseases' },
    { id: 753, testName: 'AFB Stain (ZN Stain)-Tissue', price: 250.00, category: 'Infectious Diseases' },
    { id: 754, testName: 'AFB Stain (ZN Stain)-Urine', price: 250.00, category: 'Infectious Diseases' },
    { id: 755, testName: 'Albumin-Fluid', price: 150.00, category: 'Routine Tests' },
    { id: 756, testName: 'Albumin-Serum', price: 150.00, category: 'Routine Tests' },
    { id: 757, testName: 'ACTH (Adreno Corticotrophic Hormone)', price: 1300.00, category: 'Hormonal & Endocrine' },
    { id: 758, testName: 'Aldolase', price: 900.00, category: 'Specialized Tests' },
    { id: 759, testName: '1,25-Dihydroxy Vitamin D3', price: 3200.00, category: 'Routine Tests' },
    { id: 760, testName: 'AFB Culture (LJ Method) - Ascitic Fluid', price: 650.00, category: 'Infectious Diseases' },
    { id: 761, testName: 'AFB Culture (LJ Method) - Miscellaneous', price: 650.00, category: 'Infectious Diseases' },
    { id: 762, testName: 'AFB Culture (LJ Method)- Body Fluids', price: 650.00, category: 'Infectious Diseases' },
    { id: 763, testName: 'AFB Culture (LJ Method) Bronchial lavage', price: 650.00, category: 'Infectious Diseases' },
    { id: 764, testName: 'AFB Culture (LJ Method)- CSF', price: 650.00, category: 'Infectious Diseases' },
    { id: 765, testName: 'AFB Culture (LJ Method) -Pericardial Fluid', price: 650.00, category: 'Infectious Diseases' },
    { id: 766, testName: 'AFB Culture (LJ Method) -Peritoneal Fluid', price: 650.00, category: 'Infectious Diseases' },
    { id: 767, testName: 'AFB Culture (LJ Method)- Pleural fluid', price: 650.00, category: 'Infectious Diseases' },
    { id: 768, testName: 'AFB Culture (LJ Method)- Pus', price: 650.00, category: 'Infectious Diseases' },
    { id: 769, testName: 'AFB Culture (LJ Method)- Sputum', price: 650.00, category: 'Infectious Diseases' },
    { id: 770, testName: 'AFB Culture (LJ Method) -Synovial Fluid EXAMINATION BY ZN STAIN - SYNOVIAL FLUID', price: 650.00, category: 'Infectious Diseases' },
    { id: 771, testName: 'AFB Culture (LJ Method)- Tissue', price: 650.00, category: 'Infectious Diseases' },
    { id: 772, testName: 'AFB Culture (LJ Method)- Urine', price: 650.00, category: 'Infectious Diseases' },
    { id: 773, testName: 'AFB Culture (BD MGIT) - Ascitic Fluid', price: 1050.00, category: 'Infectious Diseases' },
    { id: 774, testName: 'AFB Culture (BD MGIT) - Bronchial lavage', price: 1050.00, category: 'Infectious Diseases' },
    { id: 775, testName: 'AFB Culture (BD MGIT) - Pericardial Fluid', price: 1050.00, category: 'Infectious Diseases' },
    { id: 776, testName: 'AFB Culture (BD MGIT) - Peritoneal Fluid', price: 1050.00, category: 'Infectious Diseases' },
    { id: 777, testName: 'AFB Culture (BD MGIT) - Pleural  Fluid', price: 1050.00, category: 'Infectious Diseases' },
    { id: 778, testName: 'AFB Culture (BD MGIT) - Synovial Fluid', price: 1050.00, category: 'Infectious Diseases' },
    { id: 779, testName: 'AFB Culture (BD MGIT)- Miscellaneous', price: 1050.00, category: 'Infectious Diseases' },
    { id: 780, testName: 'AFB Culture (BD MGIT)-Body Fluids', price: 1050.00, category: 'Infectious Diseases' },
    { id: 781, testName: 'AFB Culture (BD MGIT)-CSF', price: 1050.00, category: 'Infectious Diseases' },
    { id: 782, testName: 'AFB Culture (BD MGIT)-Pus', price: 1050.00, category: 'Infectious Diseases' },
    { id: 783, testName: 'AFB Culture (BD MGIT)-Sputum', price: 1050.00, category: 'Infectious Diseases' },
    { id: 784, testName: 'AFB Culture (BD MGIT)-TissueRAPID BACTEC, TISSUE', price: 1050.00, category: 'Infectious Diseases' },
    { id: 785, testName: 'Ammonia', price: 1000.00, category: 'Specialized Tests' },
    { id: 786, testName: '5-a-Dihydrotestosterone', price: 3000.00, category: 'Hormonal & Endocrine' },
    { id: 787, testName: '17-Ketosteroids-24hrs Urine', price: 3000.00, category: 'Hormonal & Endocrine' },
    { id: 788, testName: 'Aluminium', price: 2500.00, category: 'Specialized Tests' },
    { id: 789, testName: 'Acid Phosphatase-Total', price: 250.00, category: 'Routine Tests' },
    { id: 790, testName: 'Allergy Drugs', price: 1800.00, category: 'Allergy & Immunology' },
    { id: 791, testName: 'Alpha 1 Antitrypsin-AAT', price: 1800.00, category: 'Genetic & Wellness' },
    { id: 792, testName: 'Androstenedione', price: 1600.00, category: 'Hormonal & Endocrine' },
    { id: 793, testName: 'Alcohol-Serum', price: 1200.00, category: 'Specialized Tests' },
    { id: 794, testName: 'Alcohol-Urine', price: 1200.00, category: 'Specialized Tests' },
    { id: 795, testName: '5-HIAA (Hydroxy Indole Acetic Acid)', price: 3000.00, category: 'Specialized Tests' },
    { id: 796, testName: 'Allergy Food (Non-Vegetarian)', price: 1500.00, category: 'Allergy & Immunology' },
    { id: 797, testName: 'Allergy Food (Vegetarian)', price: 1500.00, category: 'Allergy & Immunology' },
    { id: 798, testName: 'Allergy Inhalants', price: 1500.00, category: 'Allergy & Immunology' },
    { id: 799, testName: 'Acid Fast Suspectibility - 5 drugs - Mycobacterium Pure Culture - LJ', price: 2800.00, category: 'Infectious Diseases' },
    { id: 800, testName: 'Anti Dnase B', price: 1600.00, category: 'Allergy & Immunology' },
    { id: 801, testName: 'Amino Leveulinic acid-24hrs Urine', price: 2800.00, category: 'Specialized Tests' },
    { id: 802, testName: 'Acetyl Choline Receptor Antibodies(ACHR)', price: 4500.00, category: 'Allergy & Immunology' },
    { id: 803, testName: 'Acid Fast Suspectibility - 10 drugs', price: 4500.00, category: 'Infectious Diseases' },
    { id: 804, testName: 'Acid Fast Suspectibility - 10 drugs - Mycobacterium Pure Culture - MGIT', price: 9000.00, category: 'Infectious Diseases' },
    { id: 805, testName: 'Acid Fast Suspectibility - 5drugs - Mycobacterium Pure Culture - MGIT', price: 5500.00, category: 'Infectious Diseases' },
    { id: 806, testName: '17p-FISH', price: 6000.00, category: 'Genetic & Wellness' },
    { id: 807, testName: 'Acid Phosphatase - Prostatic (PAP)', price: 600.00, category: 'Cancer Markers' },
    { id: 808, testName: 'Culture, Aerobic, Miscellaneous- Automated Method', price: 600.00, category: 'Infectious Diseases' },
    { id: 809, testName: 'Culture, Aerobic, Nasal swab', price: 600.00, category: 'Infectious Diseases' },
    { id: 810, testName: 'Culture, Aerobic, Pus', price: 600.00, category: 'Infectious Diseases' },
    { id: 811, testName: 'Culture, Aerobic, Sputum', price: 600.00, category: 'Infectious Diseases' },
    { id: 812, testName: 'Culture, Aerobic, Stool', price: 600.00, category: 'Infectious Diseases' },
    { id: 813, testName: 'Culture, Aerobic, Throat swab', price: 600.00, category: 'Infectious Diseases' },
    { id: 814, testName: 'Culture, Aerobic, Vaginal sawb', price: 600.00, category: 'Infectious Diseases' },
    { id: 815, testName: 'T3 (Triiodothyronine)', price: 200.00, category: 'Hormonal & Endocrine' },
    { id: 816, testName: 'T4 (Thyroxine)', price: 200.00, category: 'Hormonal & Endocrine' },
    { id: 817, testName: 'Total IgE', price: 700.00, category: 'Allergy & Immunology' },
    { id: 818, testName: 'Phenytoin (Eptoin)', price: 950.00, category: 'Specialized Tests' },
    { id: 819, testName: 'Echinococcus Antibody IgG (Hydatid serology)', price: 2100.00, category: 'Infectious Diseases' },
    { id: 820, testName: 'Glucose Tolerance Test (GTT) 3 Samples(90)', price: 450.00, category: 'Cardiac & Diabetes' },
    { id: 821, testName: 'LH (Leutinizing Hormone)', price: 450.00, category: 'Hormonal & Endocrine' },
    { id: 822, testName: 'Prolactin (PRL)', price: 450.00, category: 'Hormonal & Endocrine' },
    { id: 823, testName: 'Hepatitis Core Antibody IgM (Anti HBc - IgM)', price: 1150.00, category: 'Infectious Diseases' },
    { id: 824, testName: 'Hepatitis Core Antibody Total (HBcAb- Total)', price: 1150.00, category: 'Infectious Diseases' },
    { id: 825, testName: 'Complete Blood Count (CBC)', price: 350.00, category: 'Routine Tests' },
    { id: 826, testName: 'Phosphorus - Serum', price: 350.00, category: 'Routine Tests' },
    { id: 827, testName: 'Packed Cell Volume(PCV)', price: 250.00, category: 'Routine Tests' },
    { id: 828, testName: 'Triglycerides (TGL)', price: 250.00, category: 'Cardiac & Diabetes' },
    { id: 829, testName: 'Treponema Pallidum Haemagglutination Assay', price: 900.00, category: 'Infectious Diseases' },
    { id: 830, testName: 'Hepatitis B envelope Antibody (AntiHBe)', price: 1100.00, category: 'Infectious Diseases' },
    { id: 831, testName: 'Hepatitis B Envelope Antigen (HBeAg)', price: 1100.00, category: 'Infectious Diseases' },
    { id: 832, testName: 'Culture, Anaerobic -OT Swab', price: 875.00, category: 'Infectious Diseases' },
    { id: 833, testName: 'Hepatitis A virus-IgG (HAV IgG)', price: 1750.00, category: 'Infectious Diseases' },
    { id: 834, testName: 'Immunoglobulin A-(IgA)', price: 875.00, category: 'Allergy & Immunology' },
    { id: 835, testName: 'Immunoglobulin G(IgG):Quantitative', price: 875.00, category: 'Allergy & Immunology' },
    { id: 836, testName: 'Immunoglobulin M(IgM):Quantitative', price: 875.00, category: 'Allergy & Immunology' },
    { id: 837, testName: 'Activated Partial Thromboplastin Time (APTT/PTTK)', price: 450.00, category: 'Cardiac & Diabetes' },
    { id: 838, testName: 'Coombs Test - Direct', price: 450.00, category: 'Specialized Tests' },
    { id: 839, testName: 'Coombs Test - Indirect', price: 450.00, category: 'Specialized Tests' },
    { id: 840, testName: 'Ferritin', price: 600.00, category: 'Routine Tests' },
    { id: 841, testName: 'HIV 1& 2 antibodies & P24 Combo', price: 1950.00, category: 'Infectious Diseases' },
    { id: 842, testName: 'Prothrombin Time (PT)', price: 450.00, category: 'Cardiac & Diabetes' },
    { id: 843, testName: 'Rheumatoid Factor, RA', price: 450.00, category: 'Allergy & Immunology' },
    { id: 844, testName: 'Widal Test (Tube Test)', price: 600.00, category: 'Infectious Diseases' },
    { id: 845, testName: 'TB Gold- IGRA (IFN-y)', price: 2600.00, category: 'Infectious Diseases' },
    { id: 846, testName: 'Progesterone-Serum', price: 650.00, category: 'Hormonal & Endocrine' },
    { id: 847, testName: 'Protein/Creatinine Ratio-Ramdom', price: 650.00, category: 'Routine Tests' },
    { id: 848, testName: 'Hemogram', price: 350.00, category: 'Routine Tests' },
    { id: 849, testName: 'Varicella Zoster Virus IgG', price: 2100.00, category: 'Infectious Diseases' },
    { id: 850, testName: 'Varicella Zoster Virus IgM', price: 2100.00, category: 'Infectious Diseases' },
    { id: 851, testName: 'Allergy Profile (Drugs,Inhalants,Non-Veg and Vegetarian', price: 7500.00, category: 'Allergy & Immunology' },
    { id: 852, testName: 'Liver-Kidney Microsome - 1 Antibody (LKM 1)', price: 2500.00, category: 'Allergy & Immunology' },
    { id: 853, testName: 'Testosterone - Total', price: 600.00, category: 'Hormonal & Endocrine' },
    { id: 854, testName: 'Free Beta HCG(600)', price: 2450.00, category: 'Cancer Markers' },
    { id: 855, testName: 'Anti TPO (Anti Thyroperoxidase/ Microsomal)', price: 1000.00, category: 'Allergy & Immunology' },
    { id: 856, testName: 'Cardiolipin Antibody, IgA', price: 800.00, category: 'Specialized Tests' },
    { id: 857, testName: 'Cardiolipin Antibody, IgG', price: 800.00, category: 'Specialized Tests' },
    { id: 858, testName: 'Cardiolipin Antibody,IgM', price: 800.00, category: 'Specialized Tests' },
    { id: 859, testName: 'Lead Random Urine', price: 1600.00, category: 'Specialized Tests' },
    { id: 860, testName: 'Prostate Specific Antigen Free', price: 800.00, category: 'Cancer Markers' },
    { id: 861, testName: 'Creatine Kinase (CK), MB', price: 550.00, category: 'Cardiac & Diabetes' },
    { id: 862, testName: 'CA19.9 - Pancreatic Cancer Marker', price: 1400.00, category: 'Cancer Markers' },
    { id: 863, testName: 'Beta Human Chorionic Gonadotropin - Serum', price: 600.00, category: 'Cancer Markers' },
    { id: 864, testName: 'Biopsy-Large(> 5 cm) Specimen', price: 1200.00, category: 'Specialized Tests' },
    { id: 865, testName: 'Culture and Sensitivity, Urine (22 drugs)', price: 600.00, category: 'Infectious Diseases' },
    { id: 866, testName: 'Culture, Aerobic, Swab', price: 600.00, category: 'Infectious Diseases' },
    { id: 867, testName: 'Culture, Aerobic, Blood', price: 600.00, category: 'Infectious Diseases' },
    { id: 868, testName: 'Estradiol (E2)', price: 600.00, category: 'Hormonal & Endocrine' },
    { id: 869, testName: 'Hepatitis E virus - IgG (HEV IgG)', price: 1200.00, category: 'Infectious Diseases' },
    { id: 870, testName: 'Hepatitis E virus - IgM (HEV IgM)', price: 1200.00, category: 'Infectious Diseases' },
    { id: 871, testName: 'Magnesium - Serum', price: 600.00, category: 'Routine Tests' },
    { id: 872, testName: 'Microalbumin / Creatinine Ratio-Urine', price: 600.00, category: 'Cardiac & Diabetes' },
    { id: 873, testName: 'PTH-Intact Parathyroid Hormone (iPTH)', price: 1200.00, category: 'Hormonal & Endocrine' },
    { id: 874, testName: 'Cytology -CSF', price: 650.00, category: 'Specialized Tests' },
    { id: 875, testName: 'Cytology -Cystic Fluids', price: 650.00, category: 'Specialized Tests' },
    { id: 876, testName: 'Cytology -Fixed Smears', price: 650.00, category: 'Specialized Tests' },
    { id: 877, testName: 'Cytology -Peritoneal Fluid', price: 650.00, category: 'Specialized Tests' },
    { id: 878, testName: 'Cytology -Fluids', price: 650.00, category: 'Specialized Tests' },
    { id: 879, testName: 'Cytology -Ascitic Fluid', price: 650.00, category: 'Specialized Tests' },
    { id: 880, testName: 'Cytology -BAL Fluid', price: 650.00, category: 'Specialized Tests' },
    { id: 881, testName: 'Cytology -FNAC-Fixed Smears', price: 650.00, category: 'Specialized Tests' },
    { id: 882, testName: 'Cytology -Others', price: 650.00, category: 'Specialized Tests' },
    { id: 883, testName: 'Cytology -Ovarian Cyst', price: 650.00, category: 'Specialized Tests' },
    { id: 884, testName: 'Cytology -Pericardial Fluid', price: 650.00, category: 'Specialized Tests' },
    { id: 885, testName: 'Cytology -Pleural Fluid', price: 650.00, category: 'Specialized Tests' },
    { id: 886, testName: 'Cytology -PUS', price: 650.00, category: 'Specialized Tests' },
    { id: 887, testName: 'Cytology -Synovial Fluid', price: 650.00, category: 'Specialized Tests' },
    { id: 888, testName: 'Cytology -Urine', price: 650.00, category: 'Specialized Tests' },
    { id: 889, testName: 'Fluid Analysis (Other Fluids)', price: 650.00, category: 'Specialized Tests' },
    { id: 890, testName: 'Fluid Analysis-Ascitic', price: 650.00, category: 'Specialized Tests' },
    { id: 891, testName: 'Fluid Analysis-CSF', price: 650.00, category: 'Specialized Tests' },
    { id: 892, testName: 'Fluid Analysis - Pericardial', price: 650.00, category: 'Specialized Tests' },
    { id: 893, testName: 'Fluid Analysis-Peritoneal', price: 650.00, category: 'Specialized Tests' },
    { id: 894, testName: 'Fluid Analysis-Pleural', price: 650.00, category: 'Specialized Tests' },
    { id: 895, testName: 'Fluid Analysis-Synovial Fluid', price: 650.00, category: 'Specialized Tests' },
    { id: 896, testName: 'Semen Analysis', price: 650.00, category: 'Hormonal & Endocrine' },
    { id: 897, testName: 'Hepatitis C Virus - HCV-Genotyping', price: 7000.00, category: 'Infectious Diseases' },
    { id: 898, testName: 'Gram Stain -  Pleural Fluid', price: 400.00, category: 'Infectious Diseases' },
    { id: 899, testName: 'Gram Stain - Ascitic Fluid', price: 400.00, category: 'Infectious Diseases' },
    { id: 900, testName: 'Gram Stain - Bodyfluids', price: 400.00, category: 'Infectious Diseases' },
    { id: 901, testName: 'Gram Stain - Bronchial lavage', price: 400.00, category: 'Infectious Diseases' },
    { id: 902, testName: 'Gram Stain - CSF', price: 400.00, category: 'Infectious Diseases' },
    { id: 903, testName: 'Gram Stain - Ear swab', price: 400.00, category: 'Infectious Diseases' },
    { id: 904, testName: 'Gram Stain - Eye swab', price: 400.00, category: 'Infectious Diseases' },
    { id: 905, testName: 'Gram Stain - Miscellaneous', price: 400.00, category: 'Infectious Diseases' },
    { id: 906, testName: 'Gram Stain - Nasal swab', price: 400.00, category: 'Infectious Diseases' },
    { id: 907, testName: 'Gram Stain - Pericardial Fluid', price: 400.00, category: 'Infectious Diseases' },
    { id: 908, testName: 'Gram Stain - Pus', price: 400.00, category: 'Infectious Diseases' },
    { id: 909, testName: 'Gram Stain - Synovial  Fluid', price: 400.00, category: 'Infectious Diseases' },
    { id: 910, testName: 'Gram Stain - Throat swab', price: 400.00, category: 'Infectious Diseases' },
    { id: 911, testName: 'Gram Stain - Tissue', price: 400.00, category: 'Infectious Diseases' },
    { id: 912, testName: 'Gram Stain - Urine', price: 400.00, category: 'Infectious Diseases' },
    { id: 913, testName: 'Gram Stain - vaginal swab', price: 400.00, category: 'Infectious Diseases' },
    { id: 914, testName: 'Rubellavirus IgG Antibody', price: 400.00, category: 'Infectious Diseases' },
    { id: 915, testName: 'Rubellavirus IgM Antibody', price: 400.00, category: 'Infectious Diseases' },
    { id: 916, testName: 'Smear for Gonococci (Endocervical Secretions)', price: 800.00, category: 'Infectious Diseases' },
    { id: 917, testName: 'Smear for Gonococci (Slides)', price: 800.00, category: 'Infectious Diseases' },
    { id: 918, testName: 'Smear for Gonococci (Urine )', price: 800.00, category: 'Infectious Diseases' },
    { id: 919, testName: 'Toxoplasma gondii IgG Antibody', price: 400.00, category: 'Infectious Diseases' },
    { id: 920, testName: 'Toxoplasma gondii IgM Antibody', price: 400.00, category: 'Infectious Diseases' },
    { id: 921, testName: 'Salmonella typhi IgG (Typhidot)', price: 450.00, category: 'Infectious Diseases' },
    { id: 922, testName: 'Salmonella typhi IgM (TYPHI DOT)', price: 450.00, category: 'Infectious Diseases' },
    { id: 923, testName: 'Uric Acid - (24 hrs Urine)', price: 450.00, category: 'Routine Tests' },
    { id: 924, testName: 'G6PD, Quantitative,Blood', price: 950.00, category: 'Genetic & Wellness' },
    { id: 925, testName: 'Hepatitis B surface Antibody Total (Anti HBs)', price: 950.00, category: 'Infectious Diseases' },
    { id: 926, testName: 'Human Growth Hormone (hGH)', price: 950.00, category: 'Hormonal & Endocrine' },
    { id: 927, testName: 'Unconjugated Estriol (uE3)', price: 1900.00, category: 'Hormonal & Endocrine' },
    { id: 928, testName: 'Anti Nuclear Antibody', price: 600.00, category: 'Allergy & Immunology' },
    { id: 929, testName: 'Hepatitis C Virus RNA - Quantitative - Viral Load', price: 6000.00, category: 'Infectious Diseases' },
    { id: 930, testName: 'Insulin - Fasting', price: 700.00, category: 'Cardiac & Diabetes' },
    { id: 931, testName: 'Insulin-Post Prandial (PP)', price: 700.00, category: 'Cardiac & Diabetes' },
    { id: 932, testName: 'Carbamazepine (Tegretol)', price: 750.00, category: 'Specialized Tests' },
    { id: 933, testName: 'Lithium', price: 750.00, category: 'Specialized Tests' },
    { id: 934, testName: 'D-DIMER, QUANTITATIVE', price: 1200.00, category: 'Cardiac & Diabetes' },
    { id: 935, testName: 'Fibrinogen Degradation Product (FDP)', price: 1300.00, category: 'Cardiac & Diabetes' },
    { id: 936, testName: 'AML- t ( 15 ; 17 ) , MLL, Inv ( 16 ) t ( 8 ; 21 ) - Karyotyping+FISH', price: 4000.00, category: 'Genetic & Wellness' },
    { id: 937, testName: 'Anti Mullerian Hormone (AMH)', price: 1800.00, category: 'Hormonal & Endocrine' },
    { id: 938, testName: 'Aspartate Aminotransferase (AST/SGOT)', price: 150.00, category: 'Routine Tests' },
    { id: 939, testName: 'C-Reactive Protein (CRP)', price: 400.00, category: 'Routine Tests' },
    { id: 940, testName: 'CD4 Absolute Count', price: 1800.00, category: 'Infectious Diseases' },
    { id: 941, testName: 'Complete Urine Analysis (CUE)', price: 100.00, category: 'Routine Tests' },
    { id: 942, testName: 'Creatinine Phospho Kinase (CPK)', price: 500.00, category: 'Cardiac & Diabetes' },
    { id: 943, testName: 'Differantial Leukocyte Count (DLC)', price: 150.00, category: 'Routine Tests' },
    { id: 944, testName: 'Fibrinogen', price: 1100.00, category: 'Cardiac & Diabetes' },
    { id: 945, testName: 'Gamma Glutamyl Transferase (GGT)', price: 200.00, category: 'Routine Tests' },
    { id: 946, testName: 'Globulin', price: 150.00, category: 'Routine Tests' },
    { id: 947, testName: 'Glycosylated Hemoglobin (HbA1c)', price: 500.00, category: 'Cardiac & Diabetes' },
    { id: 948, testName: 'Hemoglobin Variant Estimation by Hemoglobin Electrophoresis', price: 900.00, category: 'Genetic & Wellness' },
    { id: 949, testName: 'Lipase-Serum', price: 550.00, category: 'Cardiac & Diabetes' },
    { id: 950, testName: 'Prostate Specific Antigen (PSA) Total', price: 550.00, category: 'Cancer Markers' },
    { id: 951, testName: 'Protein - Total With Albumin', price: 450.00, category: 'Routine Tests' },
    { id: 952, testName: 'Protein Total Quantitative-24hrs Urine', price: 450.00, category: 'Routine Tests' },
    { id: 953, testName: 'TLC and DLC', price: 250.00, category: 'Routine Tests' },
    { id: 954, testName: 'LBC PAP Smear', price: 1750.00, category: 'Cancer Markers' },
    { id: 955, testName: 'Thrombin Time', price: 875.00, category: 'Cardiac & Diabetes' },
    { id: 956, testName: 'CA 125 - Ovarian Cancer Marker', price: 800.00, category: 'Cancer Markers' },
    { id: 957, testName: 'BIOPSY-Small Specimen (< 2cm)', price: 700.00, category: 'Specialized Tests' },
    { id: 958, testName: 'Phospholipid Antibody IgG', price: 700.00, category: 'Allergy & Immunology' },
    { id: 959, testName: 'Phospholipid Antibody IgM', price: 700.00, category: 'Allergy & Immunology' },
    { id: 960, testName: 'Scrub Typhus IgM', price: 2100.00, category: 'Infectious Diseases' },
    { id: 961, testName: 'Microalbumin-Random', price: 480.00, category: 'Cardiac & Diabetes' },
    { id: 962, testName: 'Hepatitis B Virus - Quantitative - Viral Load', price: 5500.00, category: 'Infectious Diseases' },
    { id: 963, testName: 'Zinc - Serum', price: 2000.00, category: 'Routine Tests' },
    { id: 964, testName: 'Dengue Fever IgG Antibody', price: 850.00, category: 'Infectious Diseases' },
    { id: 965, testName: 'Dengue Fever IgM Antibody', price: 850.00, category: 'Infectious Diseases' },
    { id: 966, testName: 'High Sensitivity C-Reactive Protein(hsCRP)', price: 850.00, category: 'Cardiac & Diabetes' },
    { id: 967, testName: 'CA15.3 - Breast Cancer Marker', price: 1200.00, category: 'Cancer Markers' },
    { id: 968, testName: 'Gram Stain - Sputum', price: 350.00, category: 'Infectious Diseases' },
    { id: 969, testName: 'Hepatitis B Surface Antigen(Rapid)', price: 350.00, category: 'Infectious Diseases' },
    { id: 970, testName: 'Retic Count', price: 350.00, category: 'Routine Tests' },
    { id: 971, testName: 'Sodium - Urine Random', price: 350.00, category: 'Routine Tests' },
    { id: 972, testName: 'Anti ds- DNA Antibody', price: 900.00, category: 'Allergy & Immunology' },
    { id: 973, testName: 'Cocaine-Urine', price: 1500.00, category: 'Specialized Tests' },
    { id: 974, testName: 'Bile Acids-Total - Serum', price: 2000.00, category: 'Routine Tests' },
    { id: 975, testName: 'Herpes Simplex Virus (HSV) 1 IgG', price: 550.00, category: 'Infectious Diseases' },
    { id: 976, testName: 'Herpes Simplex Virus (HSV) 1 IgM', price: 550.00, category: 'Infectious Diseases' },
    { id: 977, testName: 'Herpes Simplex Virus (HSV) 2 IgG', price: 550.00, category: 'Infectious Diseases' },
    { id: 978, testName: 'Herpes Simplex Virus (HSV) 2 IgM', price: 550.00, category: 'Infectious Diseases' },
    { id: 979, testName: 'Anti Streptolysin O Titres ASO-Titers', price: 500.00, category: 'Allergy & Immunology' },
    { id: 980, testName: 'Dengue Fever NS1 Ag-ELISA', price: 1000.00, category: 'Infectious Diseases' },
    { id: 981, testName: 'Hematuria', price: 250.00, category: 'Routine Tests' },
    { id: 982, testName: 'Lactate-CSF', price: 1000.00, category: 'Specialized Tests' },
    { id: 983, testName: 'Lactate-Plasma', price: 1000.00, category: 'Cardiac & Diabetes' },
    { id: 984, testName: 'Malarial Falciparum and Vivax Antigen (Parasite V & F)', price: 500.00, category: 'Infectious Diseases' },
    { id: 985, testName: 'AMH Profile - AMH, LH, FSH, PRL, E2, TSH', price: 3000.00, category: 'Hormonal & Endocrine' },
    { id: 986, testName: 'Cortisol -Evening (3 to 5 PM)', price: 650.00, category: 'Hormonal & Endocrine' },
    { id: 987, testName: 'Cortisol -Morning  (7 to 9 AM)', price: 650.00, category: 'Hormonal & Endocrine' },
    { id: 988, testName: 'Urine for Dysmorphic RBC', price: 650.00, category: 'Routine Tests' },
    { id: 989, testName: 'Culture, Aerobic, Blood (Pediatric Rapid)', price: 2100.00, category: 'Infectious Diseases' },
    { id: 990, testName: 'Culture, Aerobic, Blood (Rapid)', price: 2100.00, category: 'Infectious Diseases' },
    { id: 991, testName: 'Culture, Anaerobic, Body Fluid, Rapid', price: 2100.00, category: 'Infectious Diseases' },
    { id: 992, testName: 'Biopsy-Medium Specimen (upto 5cm)', price: 800.00, category: 'Specialized Tests' },
    { id: 993, testName: 'Calcium-Ionized', price: 400.00, category: 'Routine Tests' },
    { id: 994, testName: 'Carcino Embryonic Antigen (CEA)', price: 800.00, category: 'Cancer Markers' },
    { id: 995, testName: 'Cholesterol VLDL - Serum', price: 200.00, category: 'Cardiac & Diabetes' },
    { id: 996, testName: 'Copper (Serum)', price: 800.00, category: 'Routine Tests' },
    { id: 997, testName: 'Dehydroepiandrosterone Sulphate (DHEA-S)', price: 800.00, category: 'Hormonal & Endocrine' },
    { id: 998, testName: 'HIV 1 & 2 Antibody Rapid (Chromatography)', price: 400.00, category: 'Infectious Diseases' },
    { id: 999, testName: 'Procalcitonin', price: 3200.00, category: 'Infectious Diseases' },
    { id: 1000, testName: 'Valproic Acid', price: 800.00, category: 'Specialized Tests' },
    { id: 1001, testName: 'Blood Urea Nitrogen (BUN)-Serum', price: 175.00, category: 'Routine Tests' },
    { id: 1002, testName: 'Blood Urea Nitrogen (BUN)-24 hrs Urine', price: 175.00, category: 'Routine Tests' },
    { id: 1003, testName: 'VDRL- Syphilis Antibodies', price: 175.00, category: 'Infectious Diseases' },
    { id: 1004, testName: 'Dehydroepiandrosterone (DHEA)', price: 2200.00, category: 'Hormonal & Endocrine' },
    { id: 1005, testName: 'Potassium- 24 hrs Urine', price: 325.00, category: 'Routine Tests' },
    { id: 1006, testName: 'Sodium - 24hrs Urine', price: 325.00, category: 'Routine Tests' },
    { id: 1007, testName: 'Chikungunya IgG', price: 1100.00, category: 'Infectious Diseases' },
    { id: 1008, testName: 'Chikungunya IgM', price: 1100.00, category: 'Infectious Diseases' },
    { id: 1009, testName: 'C3 - Complement 3', price: 600.00, category: 'Allergy & Immunology' },
    { id: 1010, testName: 'C4 - Complement 4', price: 600.00, category: 'Allergy & Immunology' },
    { id: 1011, testName: 'Scl-70 Antibody', price: 2300.00, category: 'Allergy & Immunology' },
    { id: 1012, testName: 'AML- t ( 15 ; 17 ) , MLL, Inv ( 16 ) t ( 8 ; 21 ) - Karyotyping+FISH -Heparin', price: 3000.00, category: 'Genetic & Wellness' },
    { id: 1013, testName: 'b2 (Beta)- GLYCOPROTEIN 1-IgA', price: 1500.00, category: 'Allergy & Immunology' },
    { id: 1014, testName: 'b2 (Beta)- GLYCOPROTEIN 1-IgG', price: 1500.00, category: 'Allergy & Immunology' },
    { id: 1015, testName: 'b2 (Beta)- GLYCOPROTEIN 1-IgM', price: 1500.00, category: 'Allergy & Immunology' },
    { id: 1016, testName: 'Lactate Dehydrogenase (LDH) - Ascitic Fluid', price: 500.00, category: 'Specialized Tests' },
    { id: 1017, testName: 'Lactate Dehydrogenase (LDH) - CSF', price: 500.00, category: 'Specialized Tests' },
    { id: 1018, testName: 'Lactate Dehydrogenase (LDH) - Pleural Fluid', price: 500.00, category: 'Specialized Tests' },
    { id: 1019, testName: 'Lactate Dehydrogenase (LDH) - Serum', price: 500.00, category: 'Routine Tests' },
    { id: 1020, testName: 'Testosterone - Free', price: 1000.00, category: 'Hormonal & Endocrine' },
    { id: 1021, testName: 'Urine for Hemoglobunuria', price: 750.00, category: 'Routine Tests' },
    { id: 1022, testName: 'Aspergillus fumigatus', price: 2100.00, category: 'Infectious Diseases' },
    { id: 1023, testName: 'Apolipoprotein (APO-B)', price: 600.00, category: 'Cardiac & Diabetes' },
    { id: 1024, testName: 'Apolipoproteins A1 (APO-A1)', price: 600.00, category: 'Cardiac & Diabetes' },
    { id: 1025, testName: 'Biopsy-AFB/ZN Stain', price: 600.00, category: 'Specialized Tests' },
    { id: 1026, testName: 'Biopsy-Alcian Blue stain', price: 600.00, category: 'Specialized Tests' },
    { id: 1027, testName: 'Gram Stain - Peritoneal  Fluid', price: 400.00, category: 'Infectious Diseases' },
    { id: 1028, testName: 'Herpes Simplex Virus (HSV) 1 & 2 IgG', price: 600.00, category: 'Infectious Diseases' },
    { id: 1029, testName: 'Herpes Simplex Virus (HSV) 1 & 2 IgM', price: 600.00, category: 'Infectious Diseases' },
    { id: 1030, testName: 'Hepatitis A virus IgM (HAV- IgM)', price: 1050.00, category: 'Infectious Diseases' },
    { id: 1031, testName: 'Rheumatoid Factor, RA -Rapid', price: 350.00, category: 'Allergy & Immunology' },
    { id: 1032, testName: 'Insulin Antibodies', price: 2950.00, category: 'Allergy & Immunology' },
    { id: 1033, testName: 'Biopsy-PAS Stain', price: 900.00, category: 'Specialized Tests' },
    { id: 1034, testName: 'Biopsy-Reticulin Stain', price: 900.00, category: 'Specialized Tests' },
    { id: 1035, testName: 'C - Peptide', price: 900.00, category: 'Cardiac & Diabetes' },
    { id: 1036, testName: 'Negative Stain (India Ink)-CSF', price: 450.00, category: 'Infectious Diseases' },
    { id: 1037, testName: 'Urea - (24 hrs Urine)', price: 450.00, category: 'Routine Tests' },
    { id: 1038, testName: 'Ceruloplasmin', price: 950.00, category: 'Routine Tests' },
    { id: 1039, testName: 'Transferrin', price: 1450.00, category: 'Routine Tests' },
    { id: 1040, testName: 'Brucella Antibody,IgG', price: 1750.00, category: 'Infectious Diseases' },
    { id: 1041, testName: 'Brucella Antibody,IgM', price: 1750.00, category: 'Infectious Diseases' },
    { id: 1042, testName: 'AFB Stain (ZN Stain)-  Miscellaneous', price: 300.00, category: 'Infectious Diseases' },
    { id: 1043, testName: 'Chloride-24 hrs Urine', price: 400.00, category: 'Routine Tests' },
    { id: 1044, testName: 'Chloride-CSF', price: 400.00, category: 'Routine Tests' },
    { id: 1045, testName: 'Chloride-Serum', price: 400.00, category: 'Routine Tests' },
    { id: 1046, testName: 'Chloride-Urine Random', price: 400.00, category: 'Routine Tests' },
    { id: 1047, testName: 'Erythropoietin (EPO)', price: 1800.00, category: 'Routine Tests' },
    { id: 1048, testName: 'Glucose (Sugar) Fasting', price: 100.00, category: 'Cardiac & Diabetes' },
    { id: 1049, testName: 'Glucose Post Prandial (PP)', price: 100.00, category: 'Cardiac & Diabetes' },
    { id: 1050, testName: 'Glucose Random', price: 100.00, category: 'Cardiac & Diabetes' },
    { id: 1051, testName: 'Glucose Urine Fasting', price: 100.00, category: 'Cardiac & Diabetes' },
    { id: 1052, testName: 'Glucose Urine Post Prandial', price: 100.00, category: 'Cardiac & Diabetes' },
    { id: 1053, testName: 'Glucose Urine Random', price: 100.00, category: 'Cardiac & Diabetes' },
    { id: 1054, testName: 'Glucose, Fluid', price: 100.00, category: 'Specialized Tests' },
    { id: 1055, testName: 'Rapid Plasma Reagin (RPR Test)', price: 200.00, category: 'Infectious Diseases' },
    { id: 1056, testName: 'Culture, Aerobic - Peritoneal  Fluid', price: 875.00, category: 'Infectious Diseases' },
    { id: 1057, testName: 'Semen for Fructose', price: 875.00, category: 'Hormonal & Endocrine' },
    { id: 1058, testName: 'Jo-I antibody', price: 2300.00, category: 'Allergy & Immunology' },
    { id: 1059, testName: 'Myoglobin Serum', price: 2300.00, category: 'Cardiac & Diabetes' },
    { id: 1060, testName: 'Myoglobin Urine', price: 2300.00, category: 'Cardiac & Diabetes' },
    { id: 1061, testName: 'Calcitonin', price: 2000.00, category: 'Hormonal & Endocrine' },
    { id: 1062, testName: 'Biopsy-Extra Large', price: 1500.00, category: 'Specialized Tests' },
    { id: 1063, testName: 'Anti Streptolysin O (ASO) (Rapid)', price: 350.00, category: 'Allergy & Immunology' },
    { id: 1064, testName: 'Hepatitis C Virus IgG', price: 2100.00, category: 'Infectious Diseases' },
    { id: 1065, testName: 'HLA B 27 - PCR - Qualitative', price: 2800.00, category: 'Genetic & Wellness' },
    { id: 1066, testName: 'Cortisol 24hrs Urine', price: 850.00, category: 'Hormonal & Endocrine' },
    { id: 1067, testName: 'HCV - IgM Antibody', price: 2500.00, category: 'Infectious Diseases' },
    { id: 1068, testName: 'Bone Marrow Smear Examination', price: 900.00, category: 'Specialized Tests' },
    { id: 1069, testName: 'CD3/CD4/CD8', price: 1800.00, category: 'Infectious Diseases' },
    { id: 1070, testName: 'Creatinine Clearance Test', price: 900.00, category: 'Routine Tests' },
    { id: 1071, testName: 'Immunofixation Electrophoresis(IFE)', price: 8000.00, category: 'Specialized Tests' },
    { id: 1072, testName: 'Antithyroglobulin Antibodies (ATG)', price: 1100.00, category: 'Allergy & Immunology' },
    { id: 1073, testName: 'Culture, Anaerobic , Blood, Rapid', price: 1100.00, category: 'Infectious Diseases' },
    { id: 1074, testName: 'Leptospira Detection-Urine', price: 1100.00, category: 'Infectious Diseases' },
    { id: 1075, testName: 'Asthma/Rhintis Screening Panel - Pediatric', price: 6000.00, category: 'Allergy & Immunology' },
    { id: 1076, testName: 'Inhibin A', price: 2450.00, category: 'Hormonal & Endocrine' },
    { id: 1077, testName: 'Sm/RNP Antibody', price: 2450.00, category: 'Allergy & Immunology' },
    { id: 1078, testName: 'Bilirubin (Direct)', price: 150.00, category: 'Routine Tests' },
    { id: 1079, testName: 'Bilirubin (Indirect)', price: 150.00, category: 'Routine Tests' },
    { id: 1080, testName: 'Bilirubin (Total)', price: 150.00, category: 'Routine Tests' },
    { id: 1081, testName: 'Blood Picture - Peripheral Smear Examination', price: 150.00, category: 'Routine Tests' },
    { id: 1082, testName: 'Calcium -Serum', price: 150.00, category: 'Routine Tests' },
    { id: 1083, testName: 'Cholesterol Total', price: 150.00, category: 'Cardiac & Diabetes' },
    { id: 1084, testName: 'Creatinine - Serum', price: 150.00, category: 'Routine Tests' },
    { id: 1085, testName: 'EBV IgM Antibody to Nuclear Antigen', price: 2700.00, category: 'Infectious Diseases' },
    { id: 1086, testName: 'EBV IgM Antibody to Viral Antigen', price: 2700.00, category: 'Infectious Diseases' },
    { id: 1087, testName: 'Erythrocyte Sedimentation Rate (ESR)', price: 150.00, category: 'Routine Tests' },
    { id: 1088, testName: 'Lead Blood', price: 2700.00, category: 'Specialized Tests' },
    { id: 1089, testName: 'Lupus Anticoagulant', price: 1350.00, category: 'Allergy & Immunology' },
    { id: 1090, testName: 'Malarial Parasite Identification', price: 150.00, category: 'Infectious Diseases' },
    { id: 1091, testName: 'Mumps IgG Antibody', price: 2700.00, category: 'Infectious Diseases' },
    { id: 1092, testName: 'Mumps IgM Antibody', price: 2700.00, category: 'Infectious Diseases' },
    { id: 1093, testName: 'Potassium- Serum', price: 150.00, category: 'Routine Tests' },
    { id: 1094, testName: 'Potassium- Urine Random', price: 150.00, category: 'Routine Tests' },
    { id: 1095, testName: 'Protein - Total', price: 150.00, category: 'Routine Tests' },
    { id: 1096, testName: 'Sodium - Serum', price: 150.00, category: 'Routine Tests' },
    { id: 1097, testName: 'Total Leucocyte Count (TLC)', price: 150.00, category: 'Routine Tests' },
    { id: 1098, testName: 'Urea - Serum', price: 150.00, category: 'Routine Tests' },
    { id: 1099, testName: 'Uric Acid - Serum', price: 150.00, category: 'Routine Tests' },
    { id: 1100, testName: 'Urine -Bilirubin', price: 150.00, category: 'Routine Tests' },
    { id: 1101, testName: 'Urine- Ketone', price: 150.00, category: 'Routine Tests' },
    { id: 1102, testName: 'Urine -Protein', price: 150.00, category: 'Routine Tests' },
    { id: 1103, testName: 'Widal Test (Slide Test)', price: 150.00, category: 'Infectious Diseases' },
    { id: 1104, testName: 'HLA B-27', price: 1750.00, category: 'Genetic & Wellness' },
    { id: 1105, testName: 'Leptospira IgG Antibody', price: 1750.00, category: 'Infectious Diseases' },
    { id: 1106, testName: 'Leptospira IgM Antibody', price: 1750.00, category: 'Infectious Diseases' },
    { id: 1107, testName: 'Protein Fluid', price: 350.00, category: 'Specialized Tests' },
    { id: 1108, testName: 'Sickling test', price: 350.00, category: 'Genetic & Wellness' },
    { id: 1109, testName: 'Measles IgG Antibody', price: 2500.00, category: 'Infectious Diseases' },
    { id: 1110, testName: 'Measles IgM Antibody', price: 2500.00, category: 'Infectious Diseases' },
    { id: 1111, testName: 'Bicarbonate (HCO3)-Serum', price: 800.00, category: 'Routine Tests' },
    { id: 1112, testName: 'Biopsy-Block and Slide Return', price: 400.00, category: 'Specialized Tests' },
    { id: 1113, testName: 'Creatinine - Urine Random', price: 200.00, category: 'Routine Tests' },
    { id: 1114, testName: 'HIV 1 & 2 Antibody-Elisa', price: 400.00, category: 'Infectious Diseases' },
    { id: 1115, testName: 'Protein Electrophoresis -Serum', price: 800.00, category: 'Specialized Tests' },
    { id: 1116, testName: 'Stool for Occult Blood', price: 200.00, category: 'Routine Tests' },
    { id: 1117, testName: 'Total Iron Binding Capacity (TIBC)', price: 400.00, category: 'Routine Tests' },
    { id: 1118, testName: 'Homocysteine-Plasma', price: 1050.00, category: 'Cardiac & Diabetes' },
    { id: 1119, testName: 'Homocysteine-Serum', price: 1050.00, category: 'Cardiac & Diabetes' },
    { id: 1120, testName: 'Cryoglobulin Qualitative', price: 1300.00, category: 'Allergy & Immunology' },
    { id: 1121, testName: 'Insulin like Growth factor (IGF- I( Somatomedin-C )', price: 3900.00, category: 'Hormonal & Endocrine' },
    { id: 1122, testName: 'Lipase-Urine', price: 1300.00, category: 'Cardiac & Diabetes' },
    { id: 1123, testName: 'Protein Urinary - Random Urine', price: 325.00, category: 'Routine Tests' },
    { id: 1124, testName: 'Synovial fluid for Crystals', price: 650.00, category: 'Specialized Tests' },
    { id: 1125, testName: 'Bone Marrow Smear - Iron Stain', price: 1150.00, category: 'Specialized Tests' },
    { id: 1126, testName: 'Tissue Transglutaminase IgA Antibody', price: 900.00, category: 'Allergy & Immunology' },
    { id: 1127, testName: 'Tissue Transglutaminase IgG Antibody', price: 900.00, category: 'Allergy & Immunology' },
    { id: 1128, testName: 'Thyroid Profile - Total', price: 500.00, category: 'Hormonal & Endocrine' },
    { id: 1129, testName: 'Thyroid Profile - Free', price: 1200.00, category: 'Hormonal & Endocrine' },
    { id: 1130, testName: 'Kidney Profile (KFT)', price: 700.00, category: 'Routine Tests' },
    { id: 1131, testName: 'Liver Function Test (LFT)', price: 700.00, category: 'Routine Tests' },
    { id: 1132, testName: 'Lipid Profile', price: 600.00, category: 'Cardiac & Diabetes' },
    { id: 1133, testName: 'Iron Profile', price: 550.00, category: 'Routine Tests' },
    { id: 1134, testName: 'Tissue Transglutaminase IgM Antibody', price: 900.00, category: 'Allergy & Immunology' },
    { id: 1135, testName: 'IL-6 (INterleukin-6)', price: 2500.00, category: 'Allergy & Immunology' },
    { id: 1136, testName: 'RH Antibody - Titres', price: 875.00, category: 'Allergy & Immunology' },
    { id: 1137, testName: 'Parietal Cell Antibody', price: 2900.00, category: 'Allergy & Immunology' },
    { id: 1138, testName: 'Endomysial IgA Antibody', price: 2600.00, category: 'Allergy & Immunology' },
    { id: 1139, testName: 'Endomysial IgG Antibody', price: 2600.00, category: 'Allergy & Immunology' },
    { id: 1140, testName: 'Endomysial IgM Antibody', price: 2600.00, category: 'Allergy & Immunology' },
    { id: 1141, testName: 'JAK-2 Mutation (CMPD) Exon 12 Mutation', price: 18000.00, category: 'Cancer Markers' },
    { id: 1142, testName: 'Bence Jones Protein, Urine (BJ Protein)', price: 500.00, category: 'Cancer Markers' },
    { id: 1143, testName: 'Protein Electrophoresis - 24hrs Urine', price: 1100.00, category: 'Cancer Markers' },
    { id: 1144, testName: 'PSA/FreePSA Ratio', price: 1200.00, category: 'Cancer Markers' },
    { id: 1145, testName: 'Cholesterol - LDL', price: 250.00, category: 'Cardiac & Diabetes' },
    { id: 1146, testName: 'Cholesterol HDL', price: 250.00, category: 'Cardiac & Diabetes' },
    { id: 1147, testName: 'MTHFR (Methylenetetrahydrofolate Reductase) Gene Mutation (Homocysteinemia)', price: 5300.00, category: 'Genetic & Wellness' },
    { id: 1148, testName: 'Blood Grouping (A B O) and Rh Type', price: 100.00, category: 'Genetic & Wellness' },
    { id: 1149, testName: 'Pregnancy Test', price: 250.00, category: 'Hormonal & Endocrine' },
    { id: 1150, testName: 'Calcium - Random Urine', price: 250.00, category: 'Hormonal & Endocrine' },
    { id: 1151, testName: 'Calcium -24 Hrs Urine', price: 250.00, category: 'Hormonal & Endocrine' },
    { id: 1152, testName: 'Stool Examination', price: 175.00, category: 'Infectious Diseases' },
    { id: 1153, testName: 'Weil - Felix Test', price: 875.00, category: 'Infectious Diseases' },
    { id: 1154, testName: 'Leptospira Detection-WB-Heparin', price: 1100.00, category: 'Infectious Diseases' },
    { id: 1155, testName: 'Microfilaria Antigen - Urine', price: 875.00, category: 'Infectious Diseases' },
    { id: 1156, testName: 'Microfilaria Antigen - Serum', price: 875.00, category: 'Infectious Diseases' },
    { id: 1157, testName: 'Bilirubin (Total + Direct)', price: 150.00, category: 'Routine Tests' },
    { id: 1158, testName: 'Urea - Spot Urine', price: 325.00, category: 'Routine Tests' },
    { id: 1159, testName: 'Osmolality-Serum', price: 875.00, category: 'Routine Tests' },
    { id: 1160, testName: 'Osmolality-Urine', price: 875.00, category: 'Routine Tests' },
    { id: 1161, testName: 'Biopsy-Special Stain', price: 875.00, category: 'Specialized Tests' },
    { id: 1162, testName: 'Biopsy-Second Opinion', price: 1200.00, category: 'Specialized Tests' },
    { id: 1163, testName: 'Biopsy-Small Specimen (< 2cm)-Bone', price: 1350.00, category: 'Specialized Tests' },
    { id: 1164, testName: 'Osmotic Fragility', price: 875.00, category: 'Specialized Tests' },
    { id: 1165, testName: 'Urine for Fat Globulins', price: 350.00, category: 'Specialized Tests' },
    { id: 1166, testName: 'Urine For Hemosiderin', price: 950.00, category: 'Specialized Tests' },
    { id: 1167, testName: 'Sudan Red Stain', price: 875.00, category: 'Specialized Tests' },
    { id: 1168, testName: 'Marijuana-Urine-Random', price: 950.00, category: 'Specialized Tests' },
    { id: 1169, testName: 'Phencyclidine (PCP)', price: 950.00, category: 'Specialized Tests' },
    { id: 1170, testName: 'Phenobarbital (Gardinal)', price: 950.00, category: 'Specialized Tests' },
    { id: 1171, testName: 'Urobilinogen, Urine', price: 350.00, category: 'Routine Tests' },
    { id: 1172, testName: 'RBC Folate', price: 2700.00, category: 'Genetic & Wellness' },
    { id: 1173, testName: 'Citrate-24 hrs Urine', price: 1200.00, category: 'Routine Tests' },
    { id: 1174, testName: 'Oxalate-24 hrs Urine', price: 2600.00, category: 'Routine Tests' },
    { id: 1175, testName: 'Protein Electrophoresis -CSF', price: 2600.00, category: 'Specialized Tests' },
    { id: 1176, testName: 'SS-A (Ro) Antibody', price: 2600.00, category: 'Allergy & Immunology' },
    { id: 1177, testName: 'SS-B (La) Antibody', price: 2600.00, category: 'Allergy & Immunology' },
    { id: 1178, testName: 'Culture Fungus -(Does Not Include Anti Fungal Sensitivity) Miscellaneous', price: 1300.00, category: 'Infectious Diseases' },
    { id: 1179, testName: 'Culture, Fungus (Does not include Anti fungal sensitivity)-Body fluids', price: 1300.00, category: 'Infectious Diseases' },
    { id: 1180, testName: 'Culture, Fungus (Does not include Anti fungal sensitivity)-CSF', price: 1300.00, category: 'Infectious Diseases' },
    { id: 1181, testName: 'Culture, Fungus (Does not include Anti fungal sensitivity)-Hair', price: 1300.00, category: 'Infectious Diseases' },
    { id: 1182, testName: 'Culture, Fungus (Does not include Anti fungal sensitivity)-Nails', price: 1300.00, category: 'Infectious Diseases' },
    { id: 1183, testName: 'Culture, Fungus (Does not include Anti fungal sensitivity)-Pus', price: 1300.00, category: 'Infectious Diseases' },
    { id: 1184, testName: 'Culture, Fungus (Does not include Anti fungal sensitivity)-Skin scrapings', price: 1300.00, category: 'Infectious Diseases' },
    { id: 1185, testName: 'Culture, Fungus (Does not include Anti fungal sensitivity)-Sputum', price: 1300.00, category: 'Infectious Diseases' },
    { id: 1186, testName: 'Culture, Fungus (Does not include Anti fungal sensitivity)-Swabs', price: 1300.00, category: 'Infectious Diseases' },
    { id: 1187, testName: 'Culture, Fungus (Does not include Anti fungal sensitivity)-Urine', price: 1300.00, category: 'Infectious Diseases' },
    { id: 1188, testName: 'Culture, Nocardia (Does not include Antibiotic Sensitivity)-Pus', price: 1300.00, category: 'Infectious Diseases' },
    { id: 1189, testName: 'Culture, Nocardia (Does not include Antibiotic Sensitivity)-Sputum', price: 1300.00, category: 'Infectious Diseases' },
    { id: 1190, testName: 'Culture, Nocardia ,Tissue in Normal Saline(Does not include Antibiotic Sensitivity)', price: 1300.00, category: 'Infectious Diseases' },
    { id: 1191, testName: 'Culture, Nocardia, Swabs (Does not include Antibiotic Sensitivity)', price: 1300.00, category: 'Infectious Diseases' },
    { id: 1192, testName: 'Infectious Mononucleosis', price: 1300.00, category: 'Infectious Diseases' },
    { id: 1193, testName: 'Lipoprotein (a) - Lp(a)', price: 1300.00, category: 'Cardiac & Diabetes' },
    { id: 1194, testName: 'KOH Preparation for Fungal Elements Miscellaneous (Wet Mount)', price: 450.00, category: 'Infectious Diseases' },
    { id: 1195, testName: 'KOH Preparation for Fungal Elements Body fluids (Wet Mount)', price: 450.00, category: 'Infectious Diseases' },
    { id: 1196, testName: 'KOH Preparation for Fungal Elements CSF (Wet Mount)', price: 450.00, category: 'Infectious Diseases' },
    { id: 1197, testName: 'KOH Preparation for Fungal Elements hair (Wet Mount)', price: 450.00, category: 'Infectious Diseases' },
    { id: 1198, testName: 'KOH Preparation for Fungal Elements Nails (Wet Mount)', price: 450.00, category: 'Infectious Diseases' },
    { id: 1199, testName: 'KOH Preparation for Fungal Elements Pus (Wet Mount)', price: 450.00, category: 'Infectious Diseases' },
    { id: 1200, testName: 'KOH Preparation for Fungal Elements Skin scrapings (Wet Mount)', price: 450.00, category: 'Infectious Diseases' },
    { id: 1201, testName: 'KOH Preparation for Fungal Elements Sputum (Wet Mount)', price: 450.00, category: 'Infectious Diseases' },
    { id: 1202, testName: 'KOH Preparation for Fungal Elements Swabs (Wet Mount)', price: 450.00, category: 'Infectious Diseases' },
    { id: 1203, testName: 'KOH Preparation for Fungal Elements Urine (Wet Mount)', price: 450.00, category: 'Infectious Diseases' },
    { id: 1204, testName: 'Protein C', price: 3450.00, category: 'Specialized Tests' },
    { id: 1205, testName: 'Protein S', price: 3450.00, category: 'Specialized Tests' },
    { id: 1206, testName: 'Estimated Glomerular Filtration Rate (eGFR)', price: 350.00, category: 'Routine Tests' },
    { id: 1207, testName: 'TPMT Gene (Thiopurine Methyltransferase)', price: 9600.00, category: 'Genetic & Wellness' },
    { id: 1208, testName: 'Hepatitis B Virus - Genotyping', price: 9500.00, category: 'Infectious Diseases' },
    { id: 1209, testName: 'Inhibin - B', price: 2950.00, category: 'Hormonal & Endocrine' },
    { id: 1210, testName: 'Cryptococcus Antigen', price: 2600.00, category: 'Infectious Diseases' },
    { id: 1211, testName: 'Cryptococcus Antigen - CSF', price: 2600.00, category: 'Infectious Diseases' },
    { id: 1212, testName: 'HIV - 1 RNA Virus - Quantitative - Viral Load', price: 5600.00, category: 'Infectious Diseases' },
    { id: 1213, testName: 'Anti Neutrophilic Cytoplasmic Antibody - IFA (Qualitative)', price: 900.00, category: 'Allergy & Immunology' },
    { id: 1214, testName: 'Anti Nuclear Antibody - IFA (Qualitative)', price: 900.00, category: 'Allergy & Immunology' },
    { id: 1215, testName: 'LE Cells', price: 450.00, category: 'Allergy & Immunology' },
    { id: 1216, testName: 'Intrinsic Factor IgG Antibody', price: 3350.00, category: 'Allergy & Immunology' },
    { id: 1217, testName: 'P1NP (Total)', price: 3350.00, category: 'Cancer Markers' },
    { id: 1218, testName: 'Parvovirus B19 Antibody IgG', price: 3350.00, category: 'Infectious Diseases' },
    { id: 1219, testName: 'Parvovirus B19 Antibody IgM', price: 3350.00, category: 'Infectious Diseases' },
    { id: 1220, testName: 'Phenol', price: 3350.00, category: 'Specialized Tests' },
    { id: 1221, testName: 'Neonatal Screen (Trisomy 21, 18, 13 , X, Y)-5 Markers - FISH', price: 15000.00, category: 'Genetic & Wellness' },
    { id: 1222, testName: 'Beta Human Chorionic Gonadotropin - Urine', price: 1100.00, category: 'Hormonal & Endocrine' },
    { id: 1223, testName: 'Biopsy-Medium (upto 5 cm)-Bone', price: 1100.00, category: 'Specialized Tests' },
    { id: 1224, testName: 'Fructosamine-serum', price: 1100.00, category: 'Cardiac & Diabetes' },
    { id: 1225, testName: 'Filaria Ab IgM', price: 1100.00, category: 'Infectious Diseases' },
    { id: 1226, testName: 'Rota Virus Antigen', price: 1100.00, category: 'Infectious Diseases' },
    { id: 1227, testName: 'Stone Analysis-Renal', price: 1100.00, category: 'Specialized Tests' },
    { id: 1228, testName: 'Hepatitis B Virus - Qualitative', price: 3500.00, category: 'Infectious Diseases' },
    { id: 1229, testName: 'Hepatitis C Virus RNA - Qualitative', price: 3500.00, category: 'Infectious Diseases' },
    { id: 1230, testName: 'Tacrolimus', price: 5300.00, category: 'Specialized Tests' },
    { id: 1231, testName: 'Deletion 20 q-FISH', price: 8000.00, category: 'Genetic & Wellness' },
    { id: 1232, testName: 'Biopsy-Uterus with both Tubes and Ovaries', price: 1200.00, category: 'Specialized Tests' },
    { id: 1233, testName: 'Urine -Albumin', price: 150.00, category: 'Routine Tests' },
    { id: 1234, testName: 'Prader - Willi Syndrome-FISH', price: 12500.00, category: 'Genetic & Wellness' },
    { id: 1235, testName: 'EGFR Gene Amplification-FISH', price: 18000.00, category: 'Cancer Markers' },
    { id: 1236, testName: 'Chromosomal Analysis- Blood', price: 3200.00, category: 'Genetic & Wellness' },
    { id: 1237, testName: 'GENEXPERT MTB WITH RIFAMPICIN RESISTANCE, QUALITATIVE, SPUTUM', price: 3200.00, category: 'Infectious Diseases' },
    { id: 1238, testName: 'GENEXPERT MTB WITH RIFAMPICIN RESISTANCE, QUALITATIVE, CSF', price: 3200.00, category: 'Infectious Diseases' },
    { id: 1239, testName: 'GENEXPERT MTB WITH RIFAMPICIN RESISTANCE, QUALITATIVE, ASCITIC FLUID', price: 3200.00, category: 'Infectious Diseases' },
    { id: 1240, testName: 'GENEXPERT MTB WITH RIFAMPICIN RESISTANCE, PLEURAL FLUID', price: 3200.00, category: 'Infectious Diseases' },
    { id: 1241, testName: 'GENEXPERT (XPERT) MTB WITH RIFAMPICIN RESISTANCE, QUALITATIVE', price: 3200.00, category: 'Infectious Diseases' },
    { id: 1242, testName: 'GENEXPERT (XPERT) MTB WITH RIFAMPICIN RESISTANCE, QUALITATIVE,TISSUE', price: 3200.00, category: 'Infectious Diseases' },
    { id: 1243, testName: 'ENEXPERT (XPERT) MTB WITH RIFAMPICIN RESISTANCE, QUALITATIVE', price: 3200.00, category: 'Infectious Diseases' },
    { id: 1244, testName: 'Slide Return', price: 325.00, category: 'Specialized Tests' },
    { id: 1245, testName: 'Uric Acid-Spot Urine', price: 325.00, category: 'Routine Tests' },
    { id: 1246, testName: 'Free Lite Chains (Kappa and Lambda) - Serum', price: 5300.00, category: 'Cancer Markers' },
    { id: 1247, testName: 'Free Lite Chains (Kappa and Lambda) - Urine', price: 5300.00, category: 'Cancer Markers' },
    { id: 1248, testName: 'DMD-26 exons (Duchenne Muscular Dystrophy)', price: 11000.00, category: 'Genetic & Wellness' },
    { id: 1249, testName: 'EGFR Mutation Study (10 Common Mutations)', price: 11000.00, category: 'Cancer Markers' },
    { id: 1250, testName: 'KRAS (Colorectal Cancer Marker) Mutations', price: 11000.00, category: 'Cancer Markers' },
    { id: 1251, testName: 'KRAS (Colorectal Cancer Marker) Mutations', price: 11000.00, category: 'Cancer Markers' },
    { id: 1252, testName: 'Chromosomal Analysis- Products of Conception(POC)', price: 7200.00, category: 'Genetic & Wellness' },
    { id: 1253, testName: 'Methadone', price: 950.00, category: 'Specialized Tests' },
    { id: 1254, testName: 'Methamphetamine Amine Screen', price: 950.00, category: 'Specialized Tests' },
    { id: 1255, testName: 'Opiates Screen:Urine', price: 950.00, category: 'Specialized Tests' },
    { id: 1256, testName: 'CA 72.4- Gastic Cancer Marker', price: 3500.00, category: 'Cancer Markers' },
    { id: 1257, testName: 'del 13q-FISH', price: 7300.00, category: 'Genetic & Wellness' },
    { id: 1258, testName: 'del 13q-FISH', price: 7300.00, category: 'Genetic & Wellness' },
    { id: 1259, testName: 'Biopsy-Uterus Cervix with Both Tubes Only', price: 1100.00, category: 'Specialized Tests' },
    { id: 1260, testName: 'Biopsy-Uterus with One Tube and Ovary', price: 1100.00, category: 'Specialized Tests' },
    { id: 1261, testName: 'Biopsy-Uterus without Tubes and Ovaries', price: 1100.00, category: 'Specialized Tests' },
    { id: 1262, testName: 'Chlamydia Trachomatis IgA', price: 2500.00, category: 'Infectious Diseases' },
    { id: 1263, testName: 'Chlamydia Trachomatis IgG', price: 2500.00, category: 'Infectious Diseases' },
    { id: 1264, testName: 'Chlamydia Trachomatis IgM', price: 2500.00, category: 'Infectious Diseases' },
    { id: 1265, testName: 'Immunoglobulin Fixation Electrophoresis-Urine', price: 8000.00, category: 'Specialized Tests' },
    { id: 1266, testName: 'JAK2 (Janus Kinase 2) V617F for MPDs', price: 8000.00, category: 'Cancer Markers' },
    { id: 1267, testName: 'Prenatal Aneuploidy Detection- Amnio (2 probes- Trisomy 21 & 13)-FISH', price: 8000.00, category: 'Genetic & Wellness' },
    { id: 1268, testName: 'Prenatal Aneuploidy Detection-POC(2 probes- Trisomy 21 & 13)-FISH', price: 8000.00, category: 'Genetic & Wellness' },
    { id: 1269, testName: 'Cyclosporine', price: 3900.00, category: 'Specialized Tests' },
    { id: 1270, testName: 'Diptheria IgG', price: 3900.00, category: 'Infectious Diseases' },
    { id: 1271, testName: 'Nor Metanephrines-Free', price: 3900.00, category: 'Hormonal & Endocrine' },
    { id: 1272, testName: 't (11:14) or LSI IGH / CCND1-FISH', price: 7800.00, category: 'Genetic & Wellness' },
    { id: 1273, testName: 'Toxoplasma DNA PCR - Qualitative', price: 3900.00, category: 'Infectious Diseases' },
    { id: 1274, testName: 'Fish for 18, X & Y', price: 12500.00, category: 'Genetic & Wellness' },
    { id: 1275, testName: 'HIV 1 Western Blot', price: 2450.00, category: 'Infectious Diseases' },
    { id: 1276, testName: 'Renin Activity', price: 3200.00, category: 'Hormonal & Endocrine' },
    { id: 1277, testName: 'U1-nRNP antibodies', price: 2600.00, category: 'Allergy & Immunology' },
    { id: 1278, testName: 'MPV', price: 250.00, category: 'Routine Tests' },
    { id: 1279, testName: 'Prenatal Aneuploidy Detection- Amnio (5 probes- Trisomy 21, 18, 13; X, Y)-FISH', price: 13000.00, category: 'Genetic & Wellness' },
    { id: 1280, testName: 'Prenatal Aneuploidy Detection- Cord Blood (5 probes- Trisomy 21, 18, 13; X, Y)-FISH', price: 13000.00, category: 'Genetic & Wellness' },
    { id: 1281, testName: 'Red Cell Indices', price: 250.00, category: 'Routine Tests' },
    { id: 1282, testName: 'Cytomegalo Virus (CMV) DNA - Quantitative', price: 8800.00, category: 'Infectious Diseases' },
    { id: 1283, testName: 'Cytomegalo Virus(CMV) DNA Quantitative PCR', price: 8800.00, category: 'Infectious Diseases' },
    { id: 1284, testName: 'Cytomegalo Virus (CMV)DNA - Qualitative', price: 8800.00, category: 'Infectious Diseases' },
    { id: 1285, testName: 'HIV-DNA Virus - Qualitative', price: 3900.00, category: 'Infectious Diseases' },
    { id: 1286, testName: 'Mercury Random Urine', price: 3900.00, category: 'Specialized Tests' },
    { id: 1287, testName: 'Mercury- Serum', price: 3900.00, category: 'Specialized Tests' },
    { id: 1288, testName: 'Mercury-Hair', price: 3900.00, category: 'Specialized Tests' },
    { id: 1289, testName: 'Mercury-Nails', price: 3900.00, category: 'Specialized Tests' },
    { id: 1290, testName: 'Anti Sperm Antibody', price: 900.00, category: 'Allergy & Immunology' },
    { id: 1291, testName: 'Biopsy-Large(> 5 cm)-Bone', price: 1800.00, category: 'Specialized Tests' },
    { id: 1292, testName: 'Bleeding Time (BT) & Clotting Time (CT)', price: 400.00, category: 'Pathology' },
    { id: 1293, testName: 'Alanine Aminotransferase (ALT/SGPT)', price: 150.00, category: 'Pathology' },
    { id: 1294, testName: 'TORCH Profile (IgM)', price: 1000.00, category: 'Pathology' }
  ];

  console.log(`🧪 Seeding ${testsData.length} Tests...`);

  for (const t of testsData) {
    await prisma.test.upsert({
      where: { id: t.id },
      update: {},
      create: {
        id: t.id,
        testName: t.testName,
        price: t.price,
        category: t.category,
        isActive: true,
        // ✅ Correctly mapped fields
        slug: `test-${t.id}`, 
        specialty: "Pathology",
        description: "",
        preparation: "",
        scheduleReporting: "",
        showOnHomepage: false 
      }
    });
  }

  console.log('✅ Seeding Completed!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });