'use client';

import { useCallback, useEffect, useState } from 'react';
import axios from 'axios';
import { 
  Loader2,
  Activity,
  Utensils,
  Lock,
  CheckCircle2,
  X,
  Download,
  ShieldCheck,
  Sparkles,
  ShoppingBag,
  Calendar,
  RefreshCcw,
  Droplets,
  Moon,
  Zap,
  HeartPulse,
  Leaf
} from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { toast } from '@/lib/safe-toast';
import { useRouter } from 'next/navigation';
import jsPDF from 'jspdf';
import {
  formatHealthDateTime,
  HEALTH_PROFILE_DISCLAIMER,
  parseHealthProfile,
  parseHealthProfileJson,
  type HealthProfile
} from '@/lib/ai/healthProfile';

// --- HELPER COMPONENTS ---

const MealRow = ({ label, value }: { label: string, value: string }) => (
  <div className="flex gap-3 items-start text-sm py-1.5 border-b border-slate-50 last:border-0">
    <span className="font-bold text-slate-400 w-20 shrink-0 text-xs uppercase tracking-wider">{label}</span>
    <span className="text-slate-800 font-medium text-sm leading-snug line-clamp-2">
      {value && value.length > 2 ? value : <span className="text-slate-300 italic">Tap to view details</span>}
    </span>
  </div>
);

const LifestyleIcon = ({ type }: { type: string }) => {
  const t = type?.toLowerCase() || '';
  if (t.includes('hydrat')) return <Droplets className="text-blue-500 animate-bounce" size={20} />;
  if (t.includes('sleep') || t.includes('rest')) return <Moon className="text-indigo-500" size={20} />;
  if (t.includes('activ') || t.includes('exerc')) return <Zap className="text-yellow-500" size={20} />;
  if (t.includes('nutri') || t.includes('food')) return <Leaf className="text-green-500" size={20} />;
  return <HeartPulse className="text-rose-500" size={20} />;
};

interface DashboardProps {
  dataString: string;
  orderId: number;
  orderNumber: string;
}

export default function AiHealthDashboard({ dataString, orderId, orderNumber }: DashboardProps) {
  const router = useRouter();
  const [generating, setGenerating] = useState(false);
  const [showDietModal, setShowDietModal] = useState(false);
  const [autoRequested, setAutoRequested] = useState(false);
  
  // Safe Parse Data
  const [aiData, setAiData] = useState<HealthProfile | null>(() => parseHealthProfileJson(dataString));
  const shouldAutoGenerate = !aiData;

  const hasDiet = Array.isArray(aiData?.dietPlan?.plan) && aiData.dietPlan.plan.length > 0;
  const score = aiData?.healthScore || 0;
  const reportCount = aiData?.reportCount || 0;
  const analyzedCount = aiData?.analyzedCount || 0;
  const firstDay: any = hasDiet ? aiData?.dietPlan?.plan?.[0] ?? {} : {};
  const todayName = firstDay?.day || "Day 1";
  const lastUpdatedLabel = formatHealthDateTime(aiData?.lastUpdated || aiData?.generatedAt);
  const warnings = aiData?.warnings || [];

  const handleGenerate = useCallback(async (forceRefresh = true) => {
    setGenerating(true);
    try {
      const res = await axios.post('/api/ai/generate-diet', { 
        orderId: orderId,
        forceRefresh
      });
      if (res.data?.error) {
        toast.error(res.data.error);
        return;
      }
      const nextData = parseHealthProfile(res.data);
      setAiData(nextData);
      if (res.data.dietPlan) setShowDietModal(true);
      if (res.data.cached) toast.info("Profile is already up to date.");
      else toast.success("Analysis Updated!");
    } catch (e) {
      toast.error("Analysis failed. Try again.");
    } finally {
      setGenerating(false);
    }
  }, [orderId]);

  useEffect(() => {
    if (!shouldAutoGenerate || autoRequested || generating) return;
    setAutoRequested(true);
    void handleGenerate(false);
  }, [autoRequested, generating, handleGenerate, shouldAutoGenerate]);

  if (!aiData) {
    return (
      <div className="p-4 border border-slate-200 bg-slate-50 rounded-xl space-y-3">
        <p className="text-slate-600 text-sm">AI analysis is being prepared for this report.</p>
        <button
          onClick={() => handleGenerate(true)}
          disabled={generating}
          className="inline-flex items-center gap-2 px-3 py-2 text-xs font-bold text-white bg-slate-900 rounded-lg hover:bg-black disabled:opacity-60"
        >
          <RefreshCcw size={12} className={generating ? "animate-spin" : ""} />
          {generating ? "Generating..." : "Generate Analysis"}
        </button>
      </div>
    );
  }

  const downloadPDF = () => {
    if (!hasDiet) return;
    const doc = new jsPDF();
    doc.setFontSize(22);
    doc.text("Personalized Wellness Plan", 20, 20);
    doc.setFontSize(10);
    doc.text(`Generated by WayToLab AI - Order #${orderNumber}`, 20, 30);
    if (aiData?.generatedAt || aiData?.lastUpdated) {
      doc.text(`Generated: ${formatHealthDateTime(aiData?.generatedAt || aiData?.lastUpdated)}`, 20, 36);
    }
    
    let y = 50;
    aiData.dietPlan.plan.forEach((day: any, index: number) => {
      if (y > 270) { doc.addPage(); y = 20; }
      doc.setFont("helvetica", "bold");
      doc.text(day.day || `Day ${index + 1}`, 20, y);
      y += 8;
      doc.setFont("helvetica", "normal");
      doc.text(`- Breakfast: ${day.breakfast || '-'}`, 25, y);
      doc.text(`- Lunch: ${day.lunch || '-'}`, 25, y + 6);
      doc.text(`- Dinner: ${day.dinner || '-'}`, 25, y + 12);
      y += 25;
    });

    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(`Disclaimer: ${HEALTH_PROFILE_DISCLAIMER}`, 20, 290);
    doc.save(`Diet_Plan_${orderNumber}.pdf`);
  };

  return (
    <div className="space-y-6">
      {warnings.length > 0 && (
        <div className="text-xs text-amber-700 bg-amber-50 border border-amber-200 rounded-xl px-4 py-3">
          {warnings.join(' ')}
        </div>
      )}

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        {/* LEFT CARD: Health Score & Lifestyle */}
        <motion.div 
          initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}
          className="lg:col-span-2 bg-gradient-to-br from-indigo-50/50 to-white border border-indigo-100 rounded-[2rem] p-6 shadow-sm relative overflow-hidden flex flex-col justify-between"
        >
          <div className="absolute top-0 right-0 p-10 opacity-[0.03] pointer-events-none">
            <Activity size={300} />
          </div>

          <div className="flex flex-col md:flex-row items-center gap-8 z-10">
            {/* Speedometer */}
            <div className="relative size-40 shrink-0">
               <svg className="size-full -rotate-90" viewBox="0 0 36 36">
                 <path className="text-slate-200" d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831" fill="none" stroke="currentColor" strokeWidth="2.5" />
                 <path 
                   className={`${score > 80 ? 'text-emerald-500' : score > 50 ? 'text-amber-500' : 'text-red-500'} transition-all duration-1000 ease-out`}
                   strokeDasharray={`${score}, 100`}
                   d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831" 
                   fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round"
                 />
               </svg>
               <div className="absolute inset-0 flex flex-col items-center justify-center">
                 <span className="text-4xl font-black text-slate-800">{score}</span>
                 <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mt-1">Score</span>
               </div>
            </div>

            {/* Headline */}
            <div className="flex-1 text-center md:text-left">
               <div className="inline-flex items-center gap-2 bg-slate-900 text-white px-3 py-1 rounded-full text-[10px] font-bold uppercase tracking-wider mb-3">
                  <Sparkles size={10} className="text-yellow-400" /> Based on {reportCount} reports
               </div>
               <h3 className="text-xl font-bold text-slate-800 mb-2 leading-tight">
                 {aiData.summaryHeadline || "Your health profile is ready."}
               </h3>

               <div className="flex flex-wrap gap-2 text-[10px] text-slate-500">
                 <span className="px-2 py-1 bg-white border border-slate-200 rounded-full font-semibold">
                   Reports: {analyzedCount}/{reportCount}
                 </span>
                 {lastUpdatedLabel && (
                   <span className="px-2 py-1 bg-white border border-slate-200 rounded-full font-semibold">
                     Updated {lastUpdatedLabel}
                   </span>
                 )}
                 {aiData.model && (
                   <span className="px-2 py-1 bg-white border border-slate-200 rounded-full font-semibold">
                     Model {aiData.model}
                   </span>
                 )}
                 {aiData.cached && (
                   <span className="px-2 py-1 bg-emerald-50 border border-emerald-200 rounded-full font-semibold text-emerald-700">
                     Cached
                   </span>
                 )}
               </div>
               
               <button 
                 onClick={() => void handleGenerate(true)}
                 disabled={generating}
                 className="text-xs font-bold text-slate-500 hover:text-blue-600 flex items-center justify-center md:justify-start gap-1 bg-white px-3 py-1.5 rounded-lg transition-colors border border-slate-200 shadow-sm mt-3"
               >
                 <RefreshCcw size={12} className={generating ? "animate-spin" : ""} />
                 {generating ? "Updating..." : "Refresh Analysis"}
               </button>
            </div>
          </div>

          {/* LIFESTYLE SECTION */}
          {aiData.lifestyle && aiData.lifestyle.length > 0 && (
             <div className="mt-6 pt-6 border-t border-indigo-100 grid grid-cols-1 md:grid-cols-3 gap-3">
                {aiData.lifestyle.map((item: any, i: number) => (
                  <div key={i} className="flex items-center gap-3 bg-white p-3 rounded-xl border border-indigo-50 shadow-sm">
                     <div className="w-8 h-8 bg-indigo-50 rounded-lg flex items-center justify-center shrink-0">
                       <LifestyleIcon type={item.icon} />
                     </div>
                     <div>
                       <div className="text-xs font-bold text-slate-800">{item.title}</div>
                       <div className="text-[10px] text-slate-500 leading-tight mt-0.5">{item.desc}</div>
                     </div>
                  </div>
                ))}
             </div>
          )}
        </motion.div>

        {/* RIGHT CARD: Diet Plan */}
        <motion.div 
          className={`rounded-[2rem] p-6 flex flex-col justify-between relative overflow-hidden border ${
            hasDiet ? 'bg-gradient-to-br from-emerald-50 to-white border-emerald-100' : 'bg-slate-900 text-white border-slate-800'
          }`}
        >
          {hasDiet ? (
             <>
               <div>
                 <div className="flex items-center justify-between mb-4">
                   <div className="flex items-center gap-2 text-emerald-800 font-bold">
                     <div className="p-1.5 bg-emerald-100 rounded-lg"><Utensils size={16} /></div>
                     Today's Plan
                   </div>
                   <span className="text-[10px] font-bold bg-white px-2 py-1 rounded border border-emerald-100 text-emerald-600 uppercase truncate max-w-[80px]">
                     {todayName}
                   </span>
                 </div>
                 
                 <div className="bg-white/80 p-4 rounded-2xl border border-emerald-50 shadow-sm space-y-1 backdrop-blur-sm">
                    <MealRow label="Breakfast" value={String(firstDay?.breakfast || '')} />
                    <MealRow label="Lunch" value={String(firstDay?.lunch || '')} />
                    <MealRow label="Dinner" value={String(firstDay?.dinner || '')} />
                 </div>
               </div>
               <button onClick={() => setShowDietModal(true)} className="mt-4 w-full py-3 bg-emerald-600 text-white rounded-xl text-xs font-bold hover:bg-emerald-700 transition-all hover:shadow-lg hover:shadow-emerald-200">
                 Open Full Week Plan
               </button>
             </>
          ) : (
             <>
                <div className="absolute top-0 right-0 p-6 opacity-10 rotate-12"><Lock size={120} /></div>
                <div className="relative z-10 flex flex-col h-full justify-center">
                   <div className="w-12 h-12 bg-white/10 rounded-2xl flex items-center justify-center mb-4 text-emerald-400 backdrop-blur-md">
                     <Utensils size={24} />
                   </div>
                   <h3 className="text-xl font-bold mb-2">Personalized Diet</h3>
                   <p className="text-slate-400 text-sm mb-8 leading-relaxed">
                     Unlock a 7-day meal plan designed to improve your health score.
                   </p>
                   <button onClick={() => void handleGenerate(true)} disabled={generating} className="w-full bg-emerald-500 hover:bg-emerald-400 text-white py-3.5 rounded-xl font-bold text-sm transition-all flex items-center justify-center gap-2 shadow-lg shadow-emerald-900/20">
                     {generating ? <Loader2 className="animate-spin"/> : <CheckCircle2 size={18} />}
                     {generating ? 'Analyzing...' : 'Unlock for Free'}
                   </button>
                </div>
             </>
          )}
        </motion.div>
      </div>

      {/* RECOMMENDATIONS (Cross-Sell) */}
      {aiData.recommendations && aiData.recommendations.length > 0 && (
        <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }}>
           <div className="flex items-center gap-2 mb-4 px-1">
              <Sparkles className="text-blue-600 fill-blue-600" size={18} />
              <h3 className="font-bold text-slate-800 text-lg">Recommended Next Diagnosis</h3>
           </div>
           
           <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {aiData.recommendations.map((rec: any, idx: number) => (
                 <div key={idx} className="bg-white border border-slate-100 p-5 rounded-2xl flex flex-col sm:flex-row justify-between items-center gap-4 shadow-sm hover:shadow-md transition-shadow group">
                    <div className="flex items-start gap-4">
                       <div className="w-12 h-12 rounded-xl bg-blue-50 text-blue-600 flex items-center justify-center shrink-0 group-hover:bg-blue-600 group-hover:text-white transition-colors">
                          <ShoppingBag size={20} />
                       </div>
                       <div>
                          <div className="flex items-center gap-2 mb-1">
                             <span className="text-[10px] font-bold bg-slate-100 text-slate-500 px-1.5 py-0.5 rounded uppercase">{rec.type}</span>
                             <h4 className="font-bold text-slate-800">{rec.name}</h4>
                          </div>
                          <p className="text-xs text-slate-500 leading-relaxed max-w-sm line-clamp-2">{rec.reason}</p>
                       </div>
                    </div>
                    
                    <div className="text-right flex flex-row sm:flex-col items-center sm:items-end gap-3 w-full sm:w-auto justify-between">
                       <div className="font-bold text-lg text-slate-900">INR {rec.price}</div>
                       <button onClick={() => router.push(`/search?q=${encodeURIComponent(rec.name)}`)} className="bg-slate-900 text-white px-5 py-2 rounded-lg text-xs font-bold hover:bg-black transition-transform active:scale-95 whitespace-nowrap">
                          Book Now
                       </button>
                    </div>
                 </div>
              ))}
           </div>
        </motion.div>
      )}

      {/* DIET MODAL */}
      <AnimatePresence>
        {showDietModal && hasDiet && (
          <div className="fixed inset-0 z-[60] flex items-center justify-center p-4">
             <motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={() => setShowDietModal(false)} className="absolute inset-0 bg-slate-900/60 backdrop-blur-sm" />
             
             <motion.div initial={{scale:0.95, y:20}} animate={{scale:1, y:0}} exit={{scale:0.95, y:20}} className="bg-white w-full max-w-3xl max-h-[85vh] overflow-hidden rounded-3xl shadow-2xl relative z-10 flex flex-col">
                <div className="p-6 border-b border-slate-100 flex justify-between items-center bg-slate-50">
                   <div>
                      <h2 className="text-xl font-bold text-slate-800">Your Wellness Plan</h2>
                      <p className="text-xs text-slate-500 mt-1 flex items-center gap-1"><ShieldCheck size={12} className="text-emerald-600"/> AI Analysis of {analyzedCount || reportCount} reports</p>
                   </div>
                   <button onClick={() => setShowDietModal(false)} className="p-2 bg-white rounded-full shadow-sm text-slate-400 hover:text-slate-600 hover:rotate-90 transition-all"><X size={20}/></button>
                </div>

                <div className="flex-1 overflow-y-auto p-6 space-y-6 bg-white">
                   <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                      <div className="bg-emerald-50 p-5 rounded-2xl border border-emerald-100">
                         <h4 className="font-bold text-emerald-800 text-sm mb-3 flex items-center gap-2"><CheckCircle2 size={16}/> Foods to Include</h4>
                         <div className="flex flex-wrap gap-2">{aiData.dietPlan.include?.map((item:string, i:number) => (<span key={i} className="bg-white px-2 py-1 rounded-md text-xs font-medium text-emerald-700 shadow-sm">{item}</span>))}</div>
                      </div>
                      <div className="bg-red-50 p-5 rounded-2xl border border-red-100">
                         <h4 className="font-bold text-red-800 text-sm mb-3 flex items-center gap-2"><X size={16}/> Foods to Avoid</h4>
                         <div className="flex flex-wrap gap-2">{aiData.dietPlan.avoid?.map((item:string, i:number) => (<span key={i} className="bg-white px-2 py-1 rounded-md text-xs font-medium text-red-700 shadow-sm">{item}</span>))}</div>
                      </div>
                   </div>

                   <h3 className="font-bold text-slate-800 text-lg flex items-center gap-2"><Calendar size={20} className="text-blue-600"/> Weekly Schedule</h3>
                   <div className="space-y-3">
                      {aiData.dietPlan.plan.map((day: any, i: number) => (
                         <div key={i} className="border border-slate-100 rounded-2xl p-5 hover:bg-slate-50 transition-colors group">
                            <h4 className="font-bold text-slate-900 mb-3 text-sm flex items-center gap-2">
                              <span className="w-6 h-6 rounded-full bg-blue-100 text-blue-600 flex items-center justify-center text-xs">{i+1}</span>
                              {day.day || `Day ${i+1}`}
                            </h4>
                            <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-xs">
                               <div className="flex flex-col gap-1">
                                 <span className="font-bold text-slate-400 uppercase tracking-wider text-[10px]">Breakfast</span> 
                                 <span className="text-slate-700 font-medium group-hover:text-blue-700">{day.breakfast || "See details"}</span>
                               </div>
                               <div className="flex flex-col gap-1">
                                 <span className="font-bold text-slate-400 uppercase tracking-wider text-[10px]">Lunch</span> 
                                 <span className="text-slate-700 font-medium group-hover:text-blue-700">{day.lunch || "See details"}</span>
                               </div>
                               <div className="flex flex-col gap-1">
                                 <span className="font-bold text-slate-400 uppercase tracking-wider text-[10px]">Dinner</span> 
                                 <span className="text-slate-700 font-medium group-hover:text-blue-700">{day.dinner || "See details"}</span>
                               </div>
                            </div>
                         </div>
                      ))}
                   </div>
                </div>
                
                <div className="p-4 border-t border-slate-100 bg-slate-50 flex justify-between items-center">
                   <p className="text-[10px] text-slate-400 max-w-xs">{HEALTH_PROFILE_DISCLAIMER}</p>
                   <button onClick={downloadPDF} className="flex items-center gap-2 bg-slate-900 text-white px-6 py-3 rounded-xl font-bold text-sm hover:bg-black transition-transform active:scale-95"><Download size={16} /> Download PDF</button>
                </div>
             </motion.div>
          </div>
        )}
      </AnimatePresence>
    </div>
  );
}
